import { FormEvent, useState } from "react";
import { ChevronRight, Plus, Search, X } from "lucide-react";
import { Project, User } from "../types";
import RemoteMemberManagement from "./RemoteMemberManagement";
import ProjectAccessManagement from "./ProjectAccessManagement";

export interface OrganizationSummary { id: string; slug: string; name: string; version: number; _count?: { members: number; projectSpaces: number } }
type Level = "organizations" | "projects"; type Editor = "create-organization" | "edit-organization" | "create-project" | "edit-project" | null;
export default function OrganizationSpaceSettings({ organization, organizations, project, projects, currentUser, onSelectOrganization, onCreateOrganization, onSelectProject, onCreateProject, onUpdateOrganization, onUpdateProject, showToast }: {
  organization: OrganizationSummary; project: Project; projects: Project[]; organizations: OrganizationSummary[]; currentUser: User;
  onUpdateOrganization: (name: string) => Promise<void>; onUpdateProject: (input: { name: string; description: string }) => Promise<void>; onSelectProject: (id: string) => void; onCreateProject: (input: { name: string; key: string; description: string }) => Promise<void>; onSelectOrganization: (id: string) => void; onCreateOrganization: (name: string) => Promise<void>; showToast: (message: string, type?: "success" | "error") => void;
}) {
  const [level, setLevel] = useState<Level>("organizations"); const [tab, setTab] = useState<"list" | "access">("list"); const [query, setQuery] = useState(""); const [editor, setEditor] = useState<Editor>(null); const [saving, setSaving] = useState(false); const [organizationName, setOrganizationName] = useState(""); const [spaceDraft, setSpaceDraft] = useState({ name: "", key: "", description: "" });
  const openOrganization = (item: OrganizationSummary, target: "projects" | "access") => { onSelectOrganization(item.id); if (target === "projects") { setLevel("projects"); setTab("list"); } else { setLevel("organizations"); setTab("access"); } };
  const openProject = (item: Project, access = false) => { onSelectProject(item.id); if (access) setTab("access"); };
  const openEditor = (kind: Editor, item?: OrganizationSummary | Project) => { setEditor(kind); if (kind?.includes("organization")) setOrganizationName(item && "slug" in item ? item.name : ""); else setSpaceDraft(item && "key" in item ? { name: item.name, key: item.key, description: item.description || "" } : { name: "", key: "", description: "" }); };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!editor) return; setSaving(true); try { if (editor === "create-organization") await onCreateOrganization(organizationName.trim()); if (editor === "edit-organization") await onUpdateOrganization(organizationName.trim()); if (editor === "create-project") await onCreateProject({ ...spaceDraft, key: spaceDraft.key.toUpperCase() }); if (editor === "edit-project") await onUpdateProject({ name: spaceDraft.name.trim(), description: spaceDraft.description.trim() }); showToast(editor.startsWith("create") ? "创建成功" : "保存成功"); setEditor(null); } catch (error) { showToast(error instanceof Error ? error.message : "操作失败", "error"); } finally { setSaving(false); } };
  const orgRows = organizations.filter((item) => `${item.name} ${item.slug}`.toLowerCase().includes(query.toLowerCase())); const projectRows = projects.filter((item) => `${item.name} ${item.key}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="space-y-3"><div className="flex items-center gap-1 text-xs text-slate-400"><button onClick={() => { setLevel("organizations"); setTab("list"); }} className="font-bold text-indigo-600">组织管理</button>{level === "projects" && <><ChevronRight className="h-3.5 w-3.5"/><span>{organization.name}</span><ChevronRight className="h-3.5 w-3.5"/><span>项目空间</span></>}</div>
    <div className="flex flex-col gap-3 rounded-2xl border bg-white px-4 py-3 lg:flex-row lg:items-center lg:justify-between"><div className="flex rounded-xl bg-slate-100 p-1"><button onClick={() => setTab("list")} className={`rounded-lg px-4 py-2 text-xs font-bold ${tab === "list" ? "bg-white text-indigo-700 shadow-sm" : "text-slate-500"}`}>{level === "organizations" ? "组织列表" : "项目空间列表"}</button><button onClick={() => setTab("access")} className={`rounded-lg px-4 py-2 text-xs font-bold ${tab === "access" ? "bg-white text-indigo-700 shadow-sm" : "text-slate-500"}`}>{level === "organizations" ? "组织成员与权限" : "当前空间成员与权限"}</button></div>{tab === "list" && <div className="flex gap-2"><label className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="搜索名称或标识" className="rounded-xl border py-2 pl-9 pr-3 text-xs"/></label><button onClick={() => openEditor(level === "organizations" ? "create-organization" : "create-project")} className="inline-flex items-center gap-1 rounded-xl bg-slate-900 px-4 py-2 text-xs font-bold text-white"><Plus className="h-4 w-4"/>新增{level === "organizations" ? "组织" : "空间"}</button></div>}</div>
    {tab === "list" && <section className="overflow-hidden rounded-2xl border bg-white"><table className="w-full min-w-[820px] text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr>{level === "organizations" ? <><th className="px-5 py-3">组织</th><th>成员</th><th>项目</th><th>状态</th><th className="pr-5 text-right">操作</th></> : <><th className="px-5 py-3">项目空间</th><th>描述</th><th>状态</th><th className="pr-5 text-right">操作</th></>}</tr></thead><tbody className="divide-y">{level === "organizations" ? orgRows.map((item) => <tr key={item.id} className={item.id === organization.id ? "bg-indigo-50/50" : ""}><td className="px-5 py-4 font-bold">{item.name}<div className="font-mono text-[10px] font-normal text-slate-400">{item.slug}</div></td><td>{item._count?.members ?? 0}</td><td>{item._count?.projectSpaces ?? 0}</td><td className="text-emerald-600">启用</td><td className="pr-5 text-right"><button onClick={() => openOrganization(item, "projects")} className="font-bold text-indigo-600">查看项目空间</button><button onClick={() => openOrganization(item, "access")} className="ml-4 font-bold text-violet-600">成员权限</button><button onClick={() => { onSelectOrganization(item.id); openEditor("edit-organization", item); }} className="ml-4 text-slate-500">编辑</button></td></tr>) : projectRows.map((item) => <tr key={item.id} className={item.id === project.id ? "bg-indigo-50/50" : ""}><td className="px-5 py-4 font-bold">{item.name}<div className="font-mono text-[10px] font-normal text-slate-400">{item.key}</div></td><td className="text-slate-500">{item.description || "—"}</td><td className="text-emerald-600">启用</td><td className="pr-5 text-right"><button onClick={() => openProject(item, true)} className="font-bold text-violet-600">空间权限</button><button onClick={() => { openProject(item); openEditor("edit-project", item); }} className="ml-4 text-slate-500">编辑</button></td></tr>)}</tbody></table></section>}
    {tab === "access" && level === "organizations" && <RemoteMemberManagement scope={{ organizationId: organization.id }} currentUser={currentUser}/>}
    {tab === "access" && level === "projects" && <ProjectAccessManagement organizationId={organization.id} project={project} currentUserId={currentUser.id}/>}
    {editor && <div className="fixed inset-0 z-[120] flex items-center justify-center bg-slate-900/40 p-4 backdrop-blur-xs"><form onSubmit={submit} className="w-full max-w-xl overflow-hidden rounded-2xl bg-white shadow-2xl"><header className="flex items-center justify-between border-b px-6 py-4"><div><h3 className="text-base font-black">{editor.startsWith("create") ? "新增" : "编辑"}{editor.includes("organization") ? "组织" : "项目空间"}</h3><p className="mt-1 text-xs text-slate-400">{editor.includes("organization") ? "组织是成员、角色和项目空间的租户边界" : `从属于 ${organization.name}`}</p></div><button type="button" onClick={() => setEditor(null)}><X className="h-4 w-4 text-slate-400"/></button></header><div className="grid gap-4 p-6">{editor.includes("organization") ? <input autoFocus required minLength={2} value={organizationName} onChange={(e) => setOrganizationName(e.target.value)} placeholder="组织名称" className="rounded-xl border px-3 py-2.5 text-xs"/> : <><input autoFocus required minLength={2} value={spaceDraft.name} onChange={(e) => setSpaceDraft({ ...spaceDraft, name: e.target.value })} placeholder="空间名称" className="rounded-xl border px-3 py-2.5 text-xs"/><input disabled={editor === "edit-project"} required value={spaceDraft.key} onChange={(e) => setSpaceDraft({ ...spaceDraft, key: e.target.value.toUpperCase() })} placeholder="空间 Key" className="rounded-xl border px-3 py-2.5 font-mono text-xs disabled:bg-slate-50"/><textarea value={spaceDraft.description} onChange={(e) => setSpaceDraft({ ...spaceDraft, description: e.target.value })} placeholder="空间描述" className="h-24 resize-none rounded-xl border px-3 py-2.5 text-xs"/></>}</div><footer className="flex justify-end gap-2 border-t px-6 py-4"><button type="button" onClick={() => setEditor(null)} className="rounded-xl border px-4 py-2 text-xs">取消</button><button disabled={saving} className="rounded-xl bg-indigo-600 px-5 py-2 text-xs font-bold text-white">确认保存</button></footer></form></div>}
  </div>;
}
