import { FormEvent, useState } from "react";
import { Building2, FolderKanban, Pencil, Plus, Search, X } from "lucide-react";
import { Project } from "../types";

export interface OrganizationSummary { id: string; slug: string; name: string; version: number; _count?: { members: number; projectSpaces: number } }
type View = "organizations" | "projects";
type Editor = { type: "organization"; mode: "create" | "edit" } | { type: "project"; mode: "create" | "edit" } | null;

export default function OrganizationSpaceSettings({ organization, organizations, project, projects, onSelectOrganization, onCreateOrganization, onSelectProject, onCreateProject, onUpdateOrganization, onUpdateProject, showToast }: {
  organization: OrganizationSummary; project: Project; projects: Project[]; organizations: OrganizationSummary[];
  onUpdateOrganization: (name: string) => Promise<void>; onUpdateProject: (input: { name: string; description: string }) => Promise<void>;
  onSelectProject: (id: string) => void; onCreateProject: (input: { name: string; key: string; description: string }) => Promise<void>;
  onSelectOrganization: (id: string) => void; onCreateOrganization: (name: string) => Promise<void>; showToast: (message: string, type?: "success" | "error") => void;
}) {
  const [view, setView] = useState<View>("organizations"); const [query, setQuery] = useState(""); const [editor, setEditor] = useState<Editor>(null); const [saving, setSaving] = useState(false);
  const [organizationName, setOrganizationName] = useState(""); const [spaceDraft, setSpaceDraft] = useState({ name: "", key: "", description: "" });
  const openCreate = () => { if (view === "organizations") { setOrganizationName(""); setEditor({ type: "organization", mode: "create" }); } else { setSpaceDraft({ name: "", key: "", description: "" }); setEditor({ type: "project", mode: "create" }); } };
  const openOrganizationEdit = (item: OrganizationSummary) => { onSelectOrganization(item.id); setOrganizationName(item.name); setEditor({ type: "organization", mode: "edit" }); };
  const openProjectEdit = (item: Project) => { onSelectProject(item.id); setSpaceDraft({ name: item.name, key: item.key, description: item.description || "" }); setEditor({ type: "project", mode: "edit" }); };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!editor) return; setSaving(true); try { if (editor.type === "organization") { if (editor.mode === "create") await onCreateOrganization(organizationName.trim()); else await onUpdateOrganization(organizationName.trim()); } else if (editor.mode === "create") await onCreateProject({ ...spaceDraft, key: spaceDraft.key.toUpperCase() }); else await onUpdateProject({ name: spaceDraft.name.trim(), description: spaceDraft.description.trim() }); showToast(editor.mode === "create" ? "创建成功" : "保存成功"); setEditor(null); } catch (error) { showToast(error instanceof Error ? error.message : "操作失败", "error"); } finally { setSaving(false); } };
  const filteredOrganizations = organizations.filter((item) => `${item.name} ${item.slug}`.toLowerCase().includes(query.toLowerCase())); const filteredProjects = projects.filter((item) => `${item.name} ${item.key}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="space-y-3"><div className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white px-4 py-3 shadow-sm lg:flex-row lg:items-center lg:justify-between"><div className="flex rounded-xl bg-slate-100 p-1"><button onClick={() => setView("organizations")} className={`inline-flex items-center gap-2 rounded-lg px-4 py-2 text-xs font-bold ${view === "organizations" ? "bg-white text-indigo-700 shadow-sm" : "text-slate-500"}`}><Building2 className="h-4 w-4"/>组织 {organizations.length}</button><button onClick={() => setView("projects")} className={`inline-flex items-center gap-2 rounded-lg px-4 py-2 text-xs font-bold ${view === "projects" ? "bg-white text-indigo-700 shadow-sm" : "text-slate-500"}`}><FolderKanban className="h-4 w-4"/>项目空间 {projects.length}</button></div><div className="flex gap-2"><label className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="搜索名称或标识" className="rounded-xl border border-slate-200 py-2 pl-9 pr-3 text-xs"/></label><button onClick={openCreate} className="inline-flex items-center gap-1.5 rounded-xl bg-slate-900 px-4 py-2 text-xs font-bold text-white"><Plus className="h-4 w-4"/>新增{view === "organizations" ? "组织" : "空间"}</button></div></div>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-3"><h2 className="text-sm font-black text-slate-900">{view === "organizations" ? "组织列表" : `${organization.name} · 项目空间列表`}</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr>{view === "organizations" ? <><th className="px-5 py-3">组织名称 / 标识</th><th>成员数</th><th>项目数</th><th>状态</th><th className="pr-5 text-right">操作</th></> : <><th className="px-5 py-3">空间名称 / Key</th><th>空间描述</th><th>状态</th><th className="pr-5 text-right">操作</th></>}</tr></thead><tbody className="divide-y divide-slate-100">{view === "organizations" ? filteredOrganizations.map((item) => <tr key={item.id} onClick={() => onSelectOrganization(item.id)} className={item.id === organization.id ? "bg-indigo-50/60" : "hover:bg-slate-50"}><td className="px-5 py-4 font-bold text-slate-800">{item.name}<div className="font-mono text-[10px] font-normal text-slate-400">{item.slug}</div></td><td>{item._count?.members ?? 0}</td><td>{item._count?.projectSpaces ?? 0}</td><td><span className="text-emerald-600">启用</span></td><td className="pr-5 text-right"><button onClick={(e) => { e.stopPropagation(); openOrganizationEdit(item); }} className="inline-flex items-center gap-1 font-bold text-indigo-600"><Pencil className="h-3.5 w-3.5"/>编辑</button></td></tr>) : filteredProjects.map((item) => <tr key={item.id} onClick={() => onSelectProject(item.id)} className={item.id === project.id ? "bg-indigo-50/60" : "hover:bg-slate-50"}><td className="px-5 py-4 font-bold text-slate-800">{item.name}<div className="font-mono text-[10px] font-normal text-slate-400">{item.key}</div></td><td className="max-w-lg truncate text-slate-500">{item.description || "—"}</td><td><span className="text-emerald-600">启用</span></td><td className="pr-5 text-right"><button onClick={(e) => { e.stopPropagation(); openProjectEdit(item); }} className="inline-flex items-center gap-1 font-bold text-indigo-600"><Pencil className="h-3.5 w-3.5"/>编辑</button></td></tr>)}</tbody></table></div></section>
    {editor && <div className="fixed inset-0 z-[110] flex items-center justify-center bg-slate-900/40 p-4 backdrop-blur-xs"><form onSubmit={submit} className="w-full max-w-xl overflow-hidden rounded-2xl bg-white shadow-2xl"><header className="flex items-start justify-between border-b border-slate-100 px-6 py-4"><div><h3 className="text-base font-black text-slate-900">{editor.mode === "create" ? "新增" : "编辑"}{editor.type === "organization" ? "组织" : "项目空间"}</h3><p className="mt-1 text-xs text-slate-400">标识创建后保持不变，名称和描述可随时维护</p></div><button type="button" onClick={() => setEditor(null)}><X className="h-4 w-4 text-slate-400"/></button></header><div className="grid gap-4 p-6">{editor.type === "organization" ? <label className="space-y-2"><span className="text-xs font-bold">组织名称</span><input autoFocus required minLength={2} value={organizationName} onChange={(e) => setOrganizationName(e.target.value)} className="w-full rounded-xl border px-3 py-2.5 text-xs"/></label> : <><label className="space-y-2"><span className="text-xs font-bold">空间名称</span><input autoFocus required minLength={2} value={spaceDraft.name} onChange={(e) => setSpaceDraft({ ...spaceDraft, name: e.target.value })} className="w-full rounded-xl border px-3 py-2.5 text-xs"/></label><label className="space-y-2"><span className="text-xs font-bold">空间 Key</span><input disabled={editor.mode === "edit"} required value={spaceDraft.key} onChange={(e) => setSpaceDraft({ ...spaceDraft, key: e.target.value.toUpperCase() })} className="w-full rounded-xl border px-3 py-2.5 font-mono text-xs disabled:bg-slate-50"/></label><label className="space-y-2"><span className="text-xs font-bold">空间描述</span><textarea value={spaceDraft.description} onChange={(e) => setSpaceDraft({ ...spaceDraft, description: e.target.value })} className="h-28 w-full resize-none rounded-xl border px-3 py-2.5 text-xs"/></label></>}</div><footer className="flex justify-end gap-2 border-t border-slate-100 px-6 py-4"><button type="button" onClick={() => setEditor(null)} className="rounded-xl border px-4 py-2 text-xs">取消</button><button disabled={saving || (editor.type === "project" && editor.mode === "create" && !/^[A-Z][A-Z0-9]{1,15}$/.test(spaceDraft.key))} className="rounded-xl bg-indigo-600 px-5 py-2 text-xs font-bold text-white disabled:opacity-40">{saving ? "保存中…" : "确认保存"}</button></footer></form></div>}
  </div>;
}
