import { useEffect, useState } from "react";
import { Building2, FolderKanban, Plus, Save, Search } from "lucide-react";
import { Project } from "../types";

export interface OrganizationSummary { id: string; slug: string; name: string; version: number; _count?: { members: number; projectSpaces: number } }
type View = "organizations" | "projects";

export default function OrganizationSpaceSettings({ organization, organizations, project, projects, onSelectOrganization, onCreateOrganization, onSelectProject, onCreateProject, onUpdateOrganization, onUpdateProject, showToast }: {
  organization: OrganizationSummary; project: Project; projects: Project[]; organizations: OrganizationSummary[];
  onUpdateOrganization: (name: string) => Promise<void>; onUpdateProject: (input: { name: string; description: string }) => Promise<void>;
  onSelectProject: (id: string) => void; onCreateProject: (input: { name: string; key: string; description: string }) => Promise<void>;
  onSelectOrganization: (id: string) => void; onCreateOrganization: (name: string) => Promise<void>; showToast: (message: string, type?: "success" | "error") => void;
}) {
  const [view, setView] = useState<View>("organizations");
  const [query, setQuery] = useState("");
  const [organizationName, setOrganizationName] = useState(organization.name);
  const [spaceName, setSpaceName] = useState(project.name);
  const [spaceDescription, setSpaceDescription] = useState(project.description || "");
  const [saving, setSaving] = useState(false);
  const [creating, setCreating] = useState(false);
  const [newOrganizationName, setNewOrganizationName] = useState("");
  const [newSpace, setNewSpace] = useState({ name: "", key: "", description: "" });
  useEffect(() => setOrganizationName(organization.name), [organization.name]);
  useEffect(() => { setSpaceName(project.name); setSpaceDescription(project.description || ""); }, [project]);
  const run = async (action: () => Promise<void>, success: string) => { setSaving(true); try { await action(); showToast(success); setCreating(false); } catch (error) { showToast(error instanceof Error ? error.message : "操作失败", "error"); } finally { setSaving(false); } };
  const filteredOrganizations = organizations.filter((item) => `${item.name} ${item.slug}`.toLowerCase().includes(query.toLowerCase()));
  const filteredProjects = projects.filter((item) => `${item.name} ${item.key}`.toLowerCase().includes(query.toLowerCase()));

  return <div className="space-y-4">
    <header className="rounded-2xl border border-slate-200 bg-white px-5 py-4 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-lg font-black text-slate-900">组织与项目空间</h2><p className="mt-1 text-xs text-slate-500">组织负责成员和权限边界，项目空间承载具体研发数据。</p></div><div className="flex rounded-xl bg-slate-100 p-1"><button onClick={() => setView("organizations")} className={`inline-flex items-center gap-2 rounded-lg px-4 py-2 text-xs font-bold ${view === "organizations" ? "bg-white text-indigo-700 shadow-sm" : "text-slate-500"}`}><Building2 className="h-4 w-4"/>组织 {organizations.length}</button><button onClick={() => setView("projects")} className={`inline-flex items-center gap-2 rounded-lg px-4 py-2 text-xs font-bold ${view === "projects" ? "bg-white text-indigo-700 shadow-sm" : "text-slate-500"}`}><FolderKanban className="h-4 w-4"/>项目空间 {projects.length}</button></div></div></header>
    <div className="grid min-h-[580px] gap-4 lg:grid-cols-[minmax(0,1fr)_360px]">
      <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 px-5 py-4 md:flex-row md:items-center md:justify-between"><div><h3 className="text-sm font-black text-slate-900">{view === "organizations" ? "组织列表" : `${organization.name} · 项目空间`}</h3><p className="mt-1 text-xs text-slate-400">点击列表行切换当前管理对象</p></div><div className="flex gap-2"><label className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="搜索名称或标识" className="rounded-xl border border-slate-200 py-2 pl-9 pr-3 text-xs"/></label><button onClick={() => setCreating(true)} className="inline-flex items-center gap-1.5 rounded-xl bg-slate-900 px-4 py-2 text-xs font-bold text-white"><Plus className="h-4 w-4"/>新增</button></div></div>
        {creating && <div className="border-b border-indigo-100 bg-indigo-50/40 p-4">{view === "organizations" ? <div className="flex gap-2"><input autoFocus value={newOrganizationName} onChange={(e) => setNewOrganizationName(e.target.value)} placeholder="组织名称" className="min-w-0 flex-1 rounded-xl border border-slate-200 px-3 py-2 text-xs"/><button disabled={saving || newOrganizationName.trim().length < 2} onClick={() => void run(async () => { await onCreateOrganization(newOrganizationName.trim()); setNewOrganizationName(""); }, "组织已创建")} className="rounded-xl bg-indigo-600 px-4 py-2 text-xs font-bold text-white disabled:opacity-40">确认创建</button><button onClick={() => setCreating(false)} className="px-3 text-xs text-slate-500">取消</button></div> : <div className="grid gap-2 md:grid-cols-3"><input autoFocus value={newSpace.name} onChange={(e) => setNewSpace({ ...newSpace, name: e.target.value })} placeholder="空间名称" className="rounded-xl border border-slate-200 px-3 py-2 text-xs"/><input value={newSpace.key} onChange={(e) => setNewSpace({ ...newSpace, key: e.target.value.toUpperCase() })} placeholder="空间 KEY" className="rounded-xl border border-slate-200 px-3 py-2 font-mono text-xs"/><input value={newSpace.description} onChange={(e) => setNewSpace({ ...newSpace, description: e.target.value })} placeholder="描述（可选）" className="rounded-xl border border-slate-200 px-3 py-2 text-xs"/><div className="flex gap-2 md:col-span-3"><button disabled={saving || newSpace.name.trim().length < 2 || !/^[A-Z][A-Z0-9]{1,15}$/.test(newSpace.key)} onClick={() => void run(async () => { await onCreateProject(newSpace); setNewSpace({ name: "", key: "", description: "" }); }, "项目空间已创建")} className="rounded-xl bg-indigo-600 px-4 py-2 text-xs font-bold text-white disabled:opacity-40">确认创建</button><button onClick={() => setCreating(false)} className="px-3 text-xs text-slate-500">取消</button></div></div>}</div>}
        <div className="overflow-x-auto"><table className="w-full min-w-[660px] text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr>{view === "organizations" ? <><th className="px-5 py-3">组织名称 / 标识</th><th>成员数</th><th>项目数</th><th>状态</th></> : <><th className="px-5 py-3">空间名称 / Key</th><th>空间描述</th><th>状态</th></>}</tr></thead><tbody className="divide-y divide-slate-100">{view === "organizations" ? filteredOrganizations.map((item) => <tr key={item.id} onClick={() => onSelectOrganization(item.id)} className={`cursor-pointer ${item.id === organization.id ? "bg-indigo-50/70" : "hover:bg-slate-50"}`}><td className="px-5 py-4 font-bold text-slate-800">{item.name}<div className="mt-1 font-mono text-[10px] text-slate-400">{item.slug}</div></td><td>{item._count?.members ?? 0}</td><td>{item._count?.projectSpaces ?? 0}</td><td><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-bold text-emerald-700">启用</span></td></tr>) : filteredProjects.map((item) => <tr key={item.id} onClick={() => onSelectProject(item.id)} className={`cursor-pointer ${item.id === project.id ? "bg-indigo-50/70" : "hover:bg-slate-50"}`}><td className="px-5 py-4 font-bold text-slate-800">{item.name}<div className="mt-1 font-mono text-[10px] text-slate-400">{item.key}</div></td><td className="max-w-sm truncate text-slate-500">{item.description || "—"}</td><td><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-bold text-emerald-700">启用</span></td></tr>)}</tbody></table></div>
      </section>
      <aside className="h-fit rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-5 flex items-center gap-3"><span className="rounded-xl bg-indigo-50 p-2.5 text-indigo-600">{view === "organizations" ? <Building2 className="h-5 w-5"/> : <FolderKanban className="h-5 w-5"/>}</span><div><h3 className="text-sm font-black text-slate-900">{view === "organizations" ? "组织详情" : "项目空间详情"}</h3><p className="text-[10px] text-slate-400">修改当前选中对象</p></div></div>{view === "organizations" ? <><label className="space-y-2"><span className="text-xs font-bold text-slate-700">组织名称</span><input value={organizationName} onChange={(e) => setOrganizationName(e.target.value)} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-xs"/></label><div className="mt-4 rounded-xl bg-slate-50 p-3"><div className="text-[10px] text-slate-400">不可变内部标识</div><div className="mt-1 font-mono text-xs text-slate-700">{organization.slug}</div></div><button disabled={saving || organizationName.trim().length < 2} onClick={() => void run(() => onUpdateOrganization(organizationName.trim()), "组织已更新")} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-xs font-bold text-white disabled:opacity-40"><Save className="h-4 w-4"/>保存组织</button></> : <><label className="space-y-2"><span className="text-xs font-bold text-slate-700">空间名称</span><input value={spaceName} onChange={(e) => setSpaceName(e.target.value)} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-xs"/></label><label className="mt-4 block space-y-2"><span className="text-xs font-bold text-slate-700">空间描述</span><textarea value={spaceDescription} onChange={(e) => setSpaceDescription(e.target.value)} className="h-28 w-full resize-none rounded-xl border border-slate-200 px-3 py-2.5 text-xs"/></label><div className="mt-4 rounded-xl bg-slate-50 p-3"><div className="text-[10px] text-slate-400">不可变空间 Key</div><div className="mt-1 font-mono text-xs text-slate-700">{project.key}</div></div><button disabled={saving || spaceName.trim().length < 2} onClick={() => void run(() => onUpdateProject({ name: spaceName.trim(), description: spaceDescription.trim() }), "项目空间已更新")} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-xs font-bold text-white disabled:opacity-40"><Save className="h-4 w-4"/>保存项目空间</button></>}</aside>
    </div>
  </div>;
}
