import { ReactNode, useCallback, useEffect, useMemo, useState } from "react";
import { Plus, UserPlus, X } from "lucide-react";
import { apiRequest } from "../api/httpClient";
import { ApiOrganizationMember, ApiPermission, ApiRole } from "../features/members/api/types";

interface ProjectMember { status: "ACTIVE" | "SUSPENDED"; joinedAt: string; user: { id: string; username: string; displayName: string; email: string; roleBindings: Array<{ role: Pick<ApiRole, "id" | "code" | "name" | "scope" | "projectSpaceId"> }> } }
interface ProjectInvitation { id: string; roleIds: string[]; acceptedAt: string | null; revokedAt: string | null; expiresAt: string; user: { id: string; username: string; displayName: string }; invitedBy: { id: string; displayName: string } }
type Tab = "members" | "roles" | "invitations";
const modules: Record<string, string> = { space: "项目空间", member: "成员", requirement: "需求", defect: "缺陷", testcase: "用例", integration: "服务集成", audit: "审计" };
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) { return <div className="fixed inset-0 z-[120] flex items-center justify-center bg-slate-900/40 p-4 backdrop-blur-xs"><div className="flex max-h-[90vh] w-full max-w-3xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl"><header className="flex items-center justify-between border-b px-6 py-4"><h3 className="text-base font-black">{title}</h3><button onClick={onClose}><X className="h-4 w-4 text-slate-400"/></button></header>{children}</div></div>; }

export default function ProjectAccessManagement({ organizationId, project, currentUserId }: { organizationId: string; project: { id: string; name: string }; currentUserId: string }) {
  const root = `/organizations/${organizationId}/spaces/${project.id}`;
  const [tab, setTab] = useState<Tab>("members"); const [members, setMembers] = useState<ProjectMember[]>([]); const [organizationMembers, setOrganizationMembers] = useState<ApiOrganizationMember[]>([]); const [roles, setRoles] = useState<ApiRole[]>([]); const [permissions, setPermissions] = useState<ApiPermission[]>([]); const [message, setMessage] = useState("");
  const [memberEditor, setMemberEditor] = useState<ProjectMember | "add" | null>(null); const [selectedUserId, setSelectedUserId] = useState(""); const [selectedRoleIds, setSelectedRoleIds] = useState<string[]>([]);
  const [roleEditor, setRoleEditor] = useState<ApiRole | "new" | null>(null); const [roleDraft, setRoleDraft] = useState({ name: "", description: "", permissionCodes: [] as string[] });
  const [invitations, setInvitations] = useState<ProjectInvitation[]>([]); const [inviteOpen, setInviteOpen] = useState(false); const [inviteUserId, setInviteUserId] = useState(""); const [inviteRoleIds, setInviteRoleIds] = useState<string[]>([]);
  const load = useCallback(async () => { const [memberRows, orgRows, roleRows, permissionRows, invitationRows] = await Promise.all([apiRequest<ProjectMember[]>(`${root}/members`), apiRequest<ApiOrganizationMember[]>(`/organizations/${organizationId}/members`), apiRequest<ApiRole[]>(`${root}/roles`), apiRequest<ApiPermission[]>(`/organizations/${organizationId}/permissions`), apiRequest<ProjectInvitation[]>(`${root}/invitations`)]); setMembers(memberRows); setOrganizationMembers(orgRows); setRoles(roleRows); setPermissions(permissionRows.filter((item) => !item.code.startsWith("organization."))); setInvitations(invitationRows); }, [organizationId, root]);
  useEffect(() => { void load().catch((error) => setMessage(error instanceof Error ? error.message : "加载失败")); }, [load]);
  const grouped = useMemo(() => Object.entries(permissions.reduce<Record<string, ApiPermission[]>>((all, item) => { (all[item.code.split(".")[0]] ||= []).push(item); return all; }, {})), [permissions]);
  const run = async (action: () => Promise<unknown>, success: string) => { try { await action(); await load(); setMessage(success); } catch (error) { setMessage(error instanceof Error ? error.message : "操作失败"); } };
  const openMember = (member: ProjectMember) => { setMemberEditor(member); setSelectedRoleIds(member.user.roleBindings.map((item) => item.role.id)); };
  const saveMember = async () => { if (!memberEditor || memberEditor === "add") return; await run(() => apiRequest(`${root}/members/${memberEditor.user.id}/roles`, { method: "PUT", body: JSON.stringify({ roleIds: selectedRoleIds }) }), "项目角色已更新"); setMemberEditor(null); };
  const addMember = async () => { if (!selectedUserId) return; await run(() => apiRequest(`${root}/members`, { method: "POST", body: JSON.stringify({ userId: selectedUserId }) }), "成员已加入项目空间"); setMemberEditor(null); setSelectedUserId(""); };
  const openRole = (role: ApiRole | "new") => { setRoleEditor(role); setRoleDraft(role === "new" ? { name: "", description: "", permissionCodes: [] } : { name: role.name, description: role.description || "", permissionCodes: role.permissions.map((item) => item.permission.code) }); };
  const saveRole = async () => { if (!roleEditor) return; const input = { ...roleDraft, ...(roleEditor === "new" ? {} : { version: roleEditor.version }) }; await run(() => apiRequest(roleEditor === "new" ? `${root}/roles` : `${root}/roles/${roleEditor.id}`, { method: roleEditor === "new" ? "POST" : "PATCH", body: JSON.stringify(input) }), "项目私有角色已保存"); setRoleEditor(null); };
  const createInvitation = async () => { if (!inviteUserId) return; await run(() => apiRequest(`${root}/invitations`, { method: "POST", body: JSON.stringify({ userId: inviteUserId, roleIds: inviteRoleIds }) }), "项目邀请已创建"); setInviteOpen(false); setInviteUserId(""); setInviteRoleIds([]); };
  const available = organizationMembers.filter((member) => !members.some((item) => item.user.id === member.user.id)); const privateRoles = roles.filter((role) => role.scope === "PROJECT_SPACE" && role.projectSpaceId === project.id); const tabs: Array<[Tab, string]> = [["members", "空间成员管理"], ["roles", "本项目私有角色"], ["invitations", "项目邀请记录"]];
  return <div className="space-y-3"><div className="flex items-center justify-between"><div className="flex rounded-xl bg-slate-100 p-1">{tabs.map(([id, label]) => <button key={id} onClick={() => setTab(id)} className={`rounded-lg px-4 py-2 text-xs font-bold ${tab === id ? "bg-white text-indigo-700 shadow-sm" : "text-slate-500"}`}>{label}</button>)}</div>{message && <span className="text-xs text-indigo-600">{message}</span>}</div>
    {tab === "members" && <section className="overflow-hidden rounded-2xl border bg-white"><div className="flex items-center justify-between border-b px-5 py-4"><div><h3 className="text-sm font-black">{project.name} · 空间成员</h3><p className="mt-1 text-[11px] text-slate-400">只有加入本空间的组织成员才能访问业务数据，可叠加多个角色</p></div><button onClick={() => setMemberEditor("add")} className="inline-flex items-center gap-1.5 rounded-xl bg-slate-900 px-4 py-2 text-xs font-bold text-white"><UserPlus className="h-4 w-4"/>添加成员</button></div><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-5 py-3">成员账号</th><th>空间角色</th><th>状态</th><th className="pr-5 text-right">操作</th></tr></thead><tbody className="divide-y">{members.map((member) => <tr key={member.user.id}><td className="px-5 py-4 font-bold">{member.user.displayName}<div className="font-mono text-[10px] font-normal text-slate-400">@{member.user.username}</div></td><td>{member.user.roleBindings.map((item) => item.role.name).join("、") || "未分配"}</td><td className="text-emerald-600">{member.status === "ACTIVE" ? "正常" : "停用"}</td><td className="pr-5 text-right"><button onClick={() => openMember(member)} className="font-bold text-indigo-600">编辑空间角色</button><button onClick={() => void run(() => apiRequest(`${root}/members/${member.user.id}`, { method: "DELETE" }), "成员已移出项目")} className="ml-4 font-bold text-rose-600">移出</button></td></tr>)}</tbody></table></section>}
    {tab === "roles" && <section className="overflow-hidden rounded-2xl border bg-white"><div className="flex items-center justify-between border-b px-5 py-4"><div><h3 className="text-sm font-black">本项目私有角色</h3><p className="mt-1 text-[11px] text-slate-400">仅在“{project.name}”可见和生效</p></div><button onClick={() => openRole("new")} className="inline-flex items-center gap-1 rounded-xl bg-slate-900 px-4 py-2 text-xs font-bold text-white"><Plus className="h-4 w-4"/>新建私有角色</button></div><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-5 py-3">角色</th><th>生效范围</th><th>权限</th><th className="pr-5 text-right">操作</th></tr></thead><tbody>{privateRoles.map((role) => <tr key={role.id}><td className="px-5 py-4 font-bold">{role.name}</td><td><span className="rounded bg-sky-50 px-2 py-1 text-[10px] text-sky-700">仅当前项目</span></td><td>{role.permissions.length} 项</td><td className="pr-5 text-right"><button onClick={() => openRole(role)} className="font-bold text-indigo-600">编辑</button></td></tr>)}</tbody></table>{!privateRoles.length && <div className="py-12 text-center text-xs text-slate-400">暂无项目私有角色</div>}</section>}
    {tab === "invitations" && <section className="overflow-hidden rounded-2xl border bg-white"><div className="flex items-center justify-between border-b px-5 py-4"><div><h3 className="text-sm font-black">项目邀请记录</h3><p className="mt-1 text-[11px] text-slate-400">受邀成员接受后才获得项目访问资格</p></div><button onClick={() => setInviteOpen(true)} className="rounded-xl bg-slate-900 px-4 py-2 text-xs font-bold text-white">创建项目邀请</button></div><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-5 py-3">成员</th><th>邀请人</th><th>角色数</th><th>状态</th><th>操作</th></tr></thead><tbody>{invitations.map((item) => <tr key={item.id}><td className="px-5 py-4 font-bold">{item.user.displayName}<div className="font-mono text-[10px] font-normal text-slate-400">@{item.user.username}</div></td><td>{item.invitedBy.displayName}</td><td>{item.roleIds.length}</td><td>{item.acceptedAt ? "已接受" : item.revokedAt ? "已撤销" : new Date(item.expiresAt) < new Date() ? "已过期" : "待接受"}</td><td>{item.user.id === currentUserId && !item.acceptedAt && !item.revokedAt && <button onClick={() => void run(() => apiRequest(`${root}/invitations/${item.id}/accept`, { method: "POST" }), "已加入项目空间")} className="font-bold text-indigo-600">接受邀请</button>}</td></tr>)}</tbody></table>{!invitations.length && <div className="py-10 text-center text-xs text-slate-400">暂无项目邀请</div>}</section>}
    {memberEditor === "add" && <Modal title="从组织成员池添加到项目" onClose={() => setMemberEditor(null)}><div className="p-6"><select value={selectedUserId} onChange={(e) => setSelectedUserId(e.target.value)} className="w-full rounded-xl border px-3 py-2.5 text-xs"><option value="">选择组织成员</option>{available.map((member) => <option key={member.user.id} value={member.user.id}>{member.user.displayName} (@{member.user.username})</option>)}</select></div><footer className="flex justify-end gap-2 border-t px-6 py-4"><button onClick={() => setMemberEditor(null)} className="rounded-xl border px-4 py-2 text-xs">取消</button><button onClick={() => void addMember()} className="rounded-xl bg-indigo-600 px-5 py-2 text-xs font-bold text-white">确认添加</button></footer></Modal>}
    {memberEditor && memberEditor !== "add" && <Modal title={`编辑空间角色 · ${memberEditor.user.displayName}`} onClose={() => setMemberEditor(null)}><div className="grid gap-2 overflow-y-auto p-6 sm:grid-cols-2">{roles.map((role) => <label key={role.id} className="flex items-center gap-2 rounded-xl border p-3 text-xs"><input type="checkbox" checked={selectedRoleIds.includes(role.id)} onChange={(e) => setSelectedRoleIds(e.target.checked ? [...selectedRoleIds, role.id] : selectedRoleIds.filter((id) => id !== role.id))}/><span><b>{role.name}</b><small className="ml-2 text-slate-400">{role.scope === "ORGANIZATION" ? "组织全局" : role.projectSpaceId ? "项目私有" : "系统角色"}</small></span></label>)}</div><footer className="flex justify-end gap-2 border-t px-6 py-4"><button onClick={() => setMemberEditor(null)} className="rounded-xl border px-4 py-2 text-xs">取消</button><button onClick={() => void saveMember()} className="rounded-xl bg-indigo-600 px-5 py-2 text-xs font-bold text-white">保存角色</button></footer></Modal>}
    {roleEditor && <Modal title={roleEditor === "new" ? "新建项目私有角色" : `编辑私有角色 · ${roleEditor.name}`} onClose={() => setRoleEditor(null)}><div className="overflow-y-auto p-6"><div className="grid gap-3 md:grid-cols-2"><input value={roleDraft.name} onChange={(e) => setRoleDraft({ ...roleDraft, name: e.target.value })} placeholder="角色名称" className="rounded-xl border px-3 py-2.5 text-xs"/><input value={roleDraft.description} onChange={(e) => setRoleDraft({ ...roleDraft, description: e.target.value })} placeholder="角色说明" className="rounded-xl border px-3 py-2.5 text-xs"/></div><div className="mt-4 space-y-3">{grouped.map(([module, items]) => <fieldset key={module} className="rounded-xl border p-3"><legend className="px-2 text-xs font-black">{modules[module] || module}</legend><div className="grid gap-2 sm:grid-cols-2 md:grid-cols-3">{items.map((item) => <label key={item.code} className="flex gap-2 text-xs"><input type="checkbox" checked={roleDraft.permissionCodes.includes(item.code)} onChange={(e) => setRoleDraft({ ...roleDraft, permissionCodes: e.target.checked ? [...roleDraft.permissionCodes, item.code] : roleDraft.permissionCodes.filter((code) => code !== item.code) })}/>{item.description}</label>)}</div></fieldset>)}</div></div><footer className="flex justify-end gap-2 border-t px-6 py-4"><button onClick={() => setRoleEditor(null)} className="rounded-xl border px-4 py-2 text-xs">取消</button><button onClick={() => void saveRole()} className="rounded-xl bg-indigo-600 px-5 py-2 text-xs font-bold text-white">保存私有角色</button></footer></Modal>}
    {inviteOpen && <Modal title="创建项目邀请" onClose={() => setInviteOpen(false)}><div className="space-y-4 overflow-y-auto p-6"><select value={inviteUserId} onChange={(e) => setInviteUserId(e.target.value)} className="w-full rounded-xl border px-3 py-2.5 text-xs"><option value="">选择组织成员</option>{organizationMembers.filter((member) => !members.some((item) => item.user.id === member.user.id)).map((member) => <option key={member.user.id} value={member.user.id}>{member.user.displayName} (@{member.user.username})</option>)}</select><div className="grid gap-2 sm:grid-cols-2">{roles.map((role) => <label key={role.id} className="flex items-center gap-2 rounded-xl border p-3 text-xs"><input type="checkbox" checked={inviteRoleIds.includes(role.id)} onChange={(e) => setInviteRoleIds(e.target.checked ? [...inviteRoleIds, role.id] : inviteRoleIds.filter((id) => id !== role.id))}/>{role.name}</label>)}</div></div><footer className="flex justify-end gap-2 border-t px-6 py-4"><button onClick={() => setInviteOpen(false)} className="rounded-xl border px-4 py-2 text-xs">取消</button><button onClick={() => void createInvitation()} className="rounded-xl bg-indigo-600 px-5 py-2 text-xs font-bold text-white">发送邀请</button></footer></Modal>}
  </div>;
}
