import { ReactNode, useMemo, useState } from "react";
import { Copy, MailPlus, Pencil, Plus, X } from "lucide-react";
import { useMembers } from "../features/members/api/useMembers";
import { ApiOrganizationMember, ApiRole, CreatedInvitation, MemberApiScope } from "../features/members/api/types";
import { User } from "../types";
import SystemUserRegistry from "./SystemUserRegistry";

type Tab = "members" | "roles" | "invitations";
const permissionModules: Record<string, string> = { organization: "组织", space: "项目空间", member: "成员", requirement: "需求", defect: "缺陷", testcase: "用例", integration: "服务集成", audit: "审计" };

function Modal({ title, subtitle, onClose, children }: { title: string; subtitle: string; onClose: () => void; children: ReactNode }) {
  return <div className="fixed inset-0 z-[110] flex items-center justify-center bg-slate-900/40 p-4 backdrop-blur-xs"><div className="flex max-h-[90vh] w-full max-w-3xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl"><header className="flex items-start justify-between border-b border-slate-100 px-6 py-4"><div><h3 className="text-base font-black text-slate-900">{title}</h3><p className="mt-1 text-xs text-slate-400">{subtitle}</p></div><button onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X className="h-4 w-4"/></button></header>{children}</div></div>;
}

export default function RemoteMemberManagement({ scope, currentUser }: { scope: MemberApiScope; currentUser: User }) {
  const remote = useMembers(scope);
  const [tab, setTab] = useState<Tab>("members");
  const [message, setMessage] = useState<string | null>(null);
  const [editingMember, setEditingMember] = useState<ApiOrganizationMember | null>(null);
  const [memberDraft, setMemberDraft] = useState({ organizationRole: "" });
  const [editingRole, setEditingRole] = useState<ApiRole | "new" | null>(null);
  const [roleDraft, setRoleDraft] = useState({ name: "", description: "", permissionCodes: [] as string[] });
  const [email, setEmail] = useState(""); const [inviteRoleCode, setInviteRoleCode] = useState(""); const [created, setCreated] = useState<CreatedInvitation | null>(null);
  const organizationRoles = remote.roles.filter((role) => role.code !== "space_admin");
  const organizationPermissions = useMemo(() => remote.permissions.filter((permission) => permission.code.startsWith("organization.") || permission.code.startsWith("member.") || permission.code === "space.manage"), [remote.permissions]);
  const groupedPermissions = useMemo(() => Object.entries(organizationPermissions.reduce<Record<string, typeof remote.permissions>>((result, permission) => { const module = permission.code.split(".")[0]; (result[module] ||= []).push(permission); return result; }, {})), [organizationPermissions]);
  const run = async (action: () => Promise<unknown>, success: string) => { setMessage(null); try { await action(); setMessage(success); } catch (error) { setMessage(error instanceof Error ? error.message : "操作失败"); } };
  const openMember = (member: ApiOrganizationMember) => { setEditingMember(member); setMemberDraft({ organizationRole: member.user.roleBindings.find((b) => b.scopeType === "ORGANIZATION")?.role.code || "" }); };
  const saveMember = async () => { if (!editingMember || !memberDraft.organizationRole) return; await run(async () => { await remote.assignRole({ userId: editingMember.user.id, roleCode: memberDraft.organizationRole }); setEditingMember(null); }, "组织角色已更新"); };
  const openRole = (role: ApiRole | "new") => { setEditingRole(role); setRoleDraft(role === "new" ? { name: "", description: "", permissionCodes: [] } : { name: role.name, description: role.description || "", permissionCodes: role.permissions.map((item) => item.permission.code) }); };
  const saveRole = async () => { if (!editingRole || editingRole !== "new" && editingRole.isSystem) return; await run(async () => { if (editingRole === "new") await remote.createRole(roleDraft); else await remote.updateRole({ roleId: editingRole.id, version: editingRole.version, ...roleDraft }); setEditingRole(null); }, editingRole === "new" ? "自定义角色已创建" : "角色权限已更新"); };
  const createInvitation = async () => { if (!email.trim() || !inviteRoleCode) return; try { const result = await remote.invite({ email: email.trim().toLowerCase(), roleCode: inviteRoleCode, expiresInHours: 24 }); setCreated(result); setEmail(""); setMessage("邀请已创建，激活 Token 仅显示一次"); } catch (error) { setMessage(error instanceof Error ? error.message : "邀请创建失败"); } };
  const tabs: Array<[Tab, string, number]> = [["members", "成员管理", remote.members.length], ["roles", "组织全局角色", remote.roles.length], ["invitations", "邀请记录", remote.invitations.length]];

  return <div className="space-y-3"><div className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white px-4 py-3 shadow-sm lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-base font-black text-slate-900">成员与权限</h2><p className="text-[11px] text-slate-400">角色直接赋予成员，组织权限与项目空间权限独立维护。</p></div><nav className="flex rounded-xl bg-slate-100 p-1">{tabs.map(([id, label, count]) => <button key={id} onClick={() => setTab(id)} className={`rounded-lg px-4 py-2 text-xs font-bold ${tab === id ? "bg-white text-indigo-700 shadow-sm" : "text-slate-500"}`}>{label}<span className="ml-1.5 text-[10px] text-slate-400">{count}</span></button>)}</nav></div>
    {(remote.isLoading || remote.isSaving || remote.error || message) && <div className={`rounded-xl border px-4 py-2 text-xs font-bold ${remote.error ? "border-rose-200 bg-rose-50 text-rose-700" : "border-indigo-100 bg-indigo-50 text-indigo-700"}`}>{remote.error ? (remote.error instanceof Error ? remote.error.message : "服务异常") : remote.isSaving ? "正在保存…" : remote.isLoading ? "正在加载…" : message}</div>}
    {tab === "members" && <div className="grid gap-4 xl:grid-cols-2">{currentUser.role === "admin" && <SystemUserRegistry organizationId={scope.organizationId} currentUserId={currentUser.id} roles={remote.roles}/>}<section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h3 className="text-sm font-black text-slate-900">当前组织成员</h3><p className="mt-1 text-[11px] text-slate-400">仅维护组织级身份，项目角色在对应项目空间配置</p></div><div className="overflow-x-auto"><table className="w-full min-w-[560px] text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-5 py-3">成员</th><th>组织角色</th><th>状态</th><th>操作</th></tr></thead><tbody className="divide-y divide-slate-100">{remote.members.map((member) => { const self = member.user.id === currentUser.id; return <tr key={member.user.id}><td className="px-5 py-4 font-bold text-slate-800">{member.user.displayName}<div className="text-[10px] font-normal text-slate-400">@{member.user.username}{self ? " · 当前用户" : ""}</div></td><td>{member.user.roleBindings.find((b) => b.scopeType === "ORGANIZATION")?.role.name || "未配置"}</td><td><button disabled={self} onClick={() => void run(() => remote.updateStatus({ userId: member.user.id, status: member.status === "ACTIVE" ? "SUSPENDED" : "ACTIVE" }), "成员状态已更新")} className={member.status === "ACTIVE" ? "text-emerald-600" : "text-rose-600"}>{member.status === "ACTIVE" ? "正常" : "已停用"}</button></td><td><button onClick={() => openMember(member)} className="inline-flex items-center gap-1 font-bold text-indigo-600"><Pencil className="h-3.5 w-3.5"/>编辑组织角色</button></td></tr>; })}</tbody></table></div></section></div>}
    {tab === "roles" && <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h3 className="text-sm font-black text-slate-900">角色与权限</h3><p className="mt-1 text-[11px] text-slate-400">仅系统管理角色固定，其余角色由组织自由创建</p></div><button onClick={() => openRole("new")} className="inline-flex items-center gap-1.5 rounded-xl bg-slate-900 px-4 py-2 text-xs font-bold text-white"><Plus className="h-4 w-4"/>新建角色</button></div><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-5 py-3">角色</th><th>类型</th><th>权限数量</th><th>说明</th><th className="text-right pr-5">操作</th></tr></thead><tbody className="divide-y divide-slate-100">{remote.roles.map((role) => <tr key={role.id}><td className="px-5 py-4 font-bold text-slate-800">{role.name}</td><td>{role.isSystem ? "系统必要" : "自定义"}</td><td>{role.permissions.length} 项</td><td className="text-slate-500">{role.description || "—"}</td><td className="pr-5 text-right"><button onClick={() => openRole(role)} className="font-bold text-indigo-600">{role.isSystem ? "查看" : "编辑"}</button>{!role.isSystem && <button onClick={() => void run(() => remote.deleteRole(role.id), "角色已删除")} className="ml-4 font-bold text-rose-600">删除</button>}</td></tr>)}</tbody></table></section>}
    {tab === "invitations" && <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 px-5 py-4 lg:flex-row lg:items-center lg:justify-between"><div><h3 className="text-sm font-black text-slate-900">成员邀请</h3><p className="mt-1 text-[11px] text-slate-400">邀请账号进入当前组织</p></div><div className="flex gap-2"><input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="成员邮箱" className="rounded-xl border border-slate-200 px-3 py-2 text-xs"/><select value={inviteRoleCode} onChange={(e) => setInviteRoleCode(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2 text-xs"><option value="">选择角色</option>{organizationRoles.map((role) => <option key={role.id} value={role.code}>{role.name}</option>)}</select><button disabled={!email.trim() || !inviteRoleCode} onClick={() => void createInvitation()} className="inline-flex items-center gap-1.5 rounded-xl bg-slate-900 px-4 py-2 text-xs font-bold text-white disabled:opacity-40"><MailPlus className="h-4 w-4"/>创建邀请</button></div></div>{created && <div className="m-4 flex gap-2 rounded-xl border border-amber-200 bg-amber-50 p-3"><input readOnly value={created.activationToken} className="min-w-0 flex-1 bg-transparent font-mono text-xs"/><button onClick={() => void navigator.clipboard.writeText(created.activationToken)}><Copy className="h-4 w-4 text-amber-700"/></button></div>}<table className="w-full text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-5 py-3">邮箱</th><th>角色</th><th>有效期</th><th>状态</th></tr></thead><tbody>{remote.invitations.map((item) => <tr key={item.id}><td className="px-5 py-4">{item.email}</td><td>{item.role.name}</td><td>{new Date(item.expiresAt).toLocaleString()}</td><td>{item.acceptedAt ? "已接受" : item.revokedAt ? "已撤销" : "待激活"}</td></tr>)}</tbody></table></section>}
    {editingMember && <Modal title={`编辑组织角色 · ${editingMember.user.displayName}`} subtitle="组织角色只控制组织配置、成员池和项目创建等全局操作" onClose={() => setEditingMember(null)}><div className="overflow-y-auto p-6"><label className="space-y-2"><span className="text-xs font-bold">组织全局角色</span><select value={memberDraft.organizationRole} onChange={(e) => setMemberDraft({ organizationRole: e.target.value })} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-xs"><option value="">请选择</option>{organizationRoles.map((role) => <option key={role.id} value={role.code}>{role.name}</option>)}</select></label></div><footer className="flex justify-end gap-2 border-t border-slate-100 px-6 py-4"><button onClick={() => setEditingMember(null)} className="rounded-xl border px-4 py-2 text-xs">取消</button><button onClick={() => void saveMember()} className="rounded-xl bg-indigo-600 px-5 py-2 text-xs font-bold text-white">保存</button></footer></Modal>}
    {editingRole && <Modal title={editingRole === "new" ? "新建自定义角色" : editingRole.name} subtitle="按业务模块配置角色权限" onClose={() => setEditingRole(null)}><div className="overflow-y-auto p-6"><div className="grid gap-4 md:grid-cols-2"><input disabled={editingRole !== "new" && editingRole.isSystem} value={roleDraft.name} onChange={(e) => setRoleDraft({ ...roleDraft, name: e.target.value })} placeholder="角色名称" className="rounded-xl border border-slate-200 px-3 py-2.5 text-xs disabled:bg-slate-50"/><input disabled={editingRole !== "new" && editingRole.isSystem} value={roleDraft.description} onChange={(e) => setRoleDraft({ ...roleDraft, description: e.target.value })} placeholder="角色说明" className="rounded-xl border border-slate-200 px-3 py-2.5 text-xs disabled:bg-slate-50"/></div><div className="mt-5 space-y-3">{groupedPermissions.map(([module, permissions]) => <fieldset key={module} className="rounded-xl border p-3"><legend className="px-2 text-xs font-black">{permissionModules[module] || module}</legend><div className="grid gap-2 sm:grid-cols-2 md:grid-cols-3">{permissions.map((permission) => <label key={permission.code} className="flex items-center gap-2 text-xs text-slate-600"><input type="checkbox" disabled={editingRole !== "new" && editingRole.isSystem} checked={roleDraft.permissionCodes.includes(permission.code)} onChange={(e) => setRoleDraft({ ...roleDraft, permissionCodes: e.target.checked ? [...roleDraft.permissionCodes, permission.code] : roleDraft.permissionCodes.filter((code) => code !== permission.code) })}/>{permission.description}</label>)}</div></fieldset>)}</div></div><footer className="flex justify-end gap-2 border-t border-slate-100 px-6 py-4"><button onClick={() => setEditingRole(null)} className="rounded-xl border px-4 py-2 text-xs">关闭</button>{(editingRole === "new" || !editingRole.isSystem) && <button disabled={roleDraft.name.trim().length < 2} onClick={() => void saveRole()} className="rounded-xl bg-indigo-600 px-5 py-2 text-xs font-bold text-white disabled:opacity-40">保存</button>}</footer></Modal>}
  </div>;
}
