import { FormEvent, useCallback, useEffect, useState } from "react";
import { Plus, Search, X } from "lucide-react";
import { apiRequest } from "../api/httpClient";
import { ApiRole } from "../features/members/api/types";
interface RegisteredUser { id: string; username: string; displayName: string; email: string; feishuUserId: string | null; status: "ACTIVE" | "SUSPENDED" | "DEACTIVATED"; isSystemAdmin: boolean; version: number; organizationMembers: Array<{ organization: { id: string; name: string } }> }
export default function SystemUserRegistry({ organizationId, currentUserId, roles }: { organizationId: string; currentUserId: string; roles: ApiRole[] }) {
  const [users, setUsers] = useState<RegisteredUser[]>([]); const [query, setQuery] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false); const [creating, setCreating] = useState(false); const [editing, setEditing] = useState<RegisteredUser | null>(null); const [joining, setJoining] = useState<RegisteredUser | null>(null); const [roleCode, setRoleCode] = useState("");
  const [form, setForm] = useState({ username: "", displayName: "", email: "", password: "", feishuUserId: "" }); const [editForm, setEditForm] = useState({ displayName: "", email: "", feishuUserId: "" });
  const load = useCallback(async () => { const params = new URLSearchParams({ limit: "100" }); if (query.trim()) params.set("q", query.trim()); const result = await apiRequest<{ items: RegisteredUser[] }>(`/users?${params}`); setUsers(result.items); }, [query]);
  useEffect(() => { const timer = setTimeout(() => void load().catch((error) => setMessage(error instanceof Error ? error.message : "账号加载失败")), 200); return () => clearTimeout(timer); }, [load]);
  const create = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { await apiRequest("/users", { method: "POST", body: JSON.stringify({ ...form, feishuUserId: form.feishuUserId || undefined }) }); setCreating(false); setForm({ username: "", displayName: "", email: "", password: "", feishuUserId: "" }); await load(); setMessage("系统账号已创建，可按需拉入组织"); } catch (error) { setMessage(error instanceof Error ? error.message : "创建失败"); } finally { setSaving(false); } };
  const saveEdit = async (event: FormEvent) => { event.preventDefault(); if (!editing) return; setSaving(true); try { await apiRequest(`/users/${editing.id}`, { method: "PATCH", body: JSON.stringify({ version: editing.version, ...editForm }) }); setEditing(null); await load(); setMessage("账号资料已更新"); } catch (error) { setMessage(error instanceof Error ? error.message : "保存失败"); } finally { setSaving(false); } };
  const join = async () => { if (!joining || !roleCode) return; setSaving(true); try { await apiRequest(`/organizations/${organizationId}/members`, { method: "POST", body: JSON.stringify({ userId: joining.id, roleCode }) }); setJoining(null); await load(); setMessage("账号已加入当前组织"); } catch (error) { setMessage(error instanceof Error ? error.message : "加入失败"); } finally { setSaving(false); } };
  const toggle = async (user: RegisteredUser) => { setSaving(true); try { await apiRequest(`/users/${user.id}`, { method: "PATCH", body: JSON.stringify({ version: user.version, status: user.status === "ACTIVE" ? "DEACTIVATED" : "ACTIVE" }) }); await load(); } finally { setSaving(false); } };
  const availableRoles = roles.filter((role) => role.scope === "ORGANIZATION");
  return <section className="overflow-hidden rounded-2xl border bg-white"><div className="flex flex-col gap-3 border-b px-5 py-4 md:flex-row md:items-center md:justify-between"><div><h3 className="text-sm font-black">系统注册账号</h3><p className="mt-1 text-[11px] text-slate-400">全局账号池；账号只能归属一个组织</p></div><div className="flex gap-2"><label className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="搜索账号" className="w-48 rounded-xl border py-2 pl-9 pr-3 text-xs"/></label><button onClick={() => setCreating(true)} className="inline-flex items-center gap-1 rounded-xl bg-slate-900 px-3 py-2 text-xs font-bold text-white"><Plus className="h-4 w-4"/>添加账号</button></div></div>{message && <div className="mx-4 mt-3 rounded-lg bg-indigo-50 px-3 py-2 text-xs text-indigo-700">{message}</div>}<table className="w-full min-w-[560px] text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-5 py-3">账号 / 姓名</th><th>归属组织</th><th>状态</th><th>操作</th></tr></thead><tbody className="divide-y">{users.map((user) => { const inCurrent = user.organizationMembers.some((item) => item.organization.id === organizationId); const assigned = user.organizationMembers[0]; return <tr key={user.id}><td className="px-5 py-4 font-bold">@{user.username}<div className="text-[10px] font-normal text-slate-400">{user.displayName}</div></td><td>{assigned?.organization.name || "未归属"}</td><td><button disabled={user.id === currentUserId} onClick={() => void toggle(user)} className={user.status === "ACTIVE" ? "text-emerald-600" : "text-rose-600"}>{user.status === "ACTIVE" ? "启用" : "禁用"}</button></td><td><button onClick={() => { setEditing(user); setEditForm({ displayName: user.displayName, email: user.email, feishuUserId: user.feishuUserId || "" }); }} className="font-bold text-indigo-600">编辑</button>{!assigned && <button onClick={() => { setJoining(user); setRoleCode(availableRoles[0]?.code || ""); }} className="ml-3 font-bold text-violet-600">拉入组织</button>}{inCurrent && <span className="ml-3 text-[10px] text-emerald-600">已在本组织</span>}</td></tr>; })}</tbody></table>
    {creating && <div className="fixed inset-0 z-[130] flex items-center justify-center bg-slate-900/40 p-4"><form onSubmit={create} className="w-full max-w-2xl overflow-hidden rounded-2xl bg-white"><header className="flex justify-between border-b px-6 py-4"><div><h3 className="font-black">添加系统注册账号</h3><p className="text-xs text-slate-400">仅创建登录账号，不自动加入组织</p></div><button type="button" onClick={() => setCreating(false)}><X className="h-4 w-4"/></button></header><div className="grid gap-3 p-6 md:grid-cols-2">{([["username","登录账号"],["displayName","显示名称"],["email","联系邮箱"],["password","初始密码（至少12位）"],["feishuUserId","飞书 User ID（可选）"]] as const).map(([key, placeholder]) => <input key={key} required={key !== "feishuUserId"} type={key === "password" ? "password" : key === "email" ? "email" : "text"} minLength={key === "password" ? 12 : undefined} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} placeholder={placeholder} className="rounded-xl border px-3 py-2.5 text-xs"/>)}</div><footer className="flex justify-end gap-2 border-t px-6 py-4"><button type="button" onClick={() => setCreating(false)} className="rounded-xl border px-4 py-2 text-xs">取消</button><button disabled={saving} className="rounded-xl bg-indigo-600 px-5 py-2 text-xs font-bold text-white">创建账号</button></footer></form></div>}
    {editing && <div className="fixed inset-0 z-[130] flex items-center justify-center bg-slate-900/40 p-4"><form onSubmit={saveEdit} className="w-full max-w-xl overflow-hidden rounded-2xl bg-white"><header className="flex justify-between border-b px-6 py-4"><h3 className="font-black">编辑账号 · @{editing.username}</h3><button type="button" onClick={() => setEditing(null)}><X className="h-4 w-4"/></button></header><div className="grid gap-3 p-6"><input value={editForm.displayName} onChange={(e) => setEditForm({ ...editForm, displayName: e.target.value })} className="rounded-xl border px-3 py-2.5 text-xs"/><input type="email" value={editForm.email} onChange={(e) => setEditForm({ ...editForm, email: e.target.value })} className="rounded-xl border px-3 py-2.5 text-xs"/><input value={editForm.feishuUserId} onChange={(e) => setEditForm({ ...editForm, feishuUserId: e.target.value })} className="rounded-xl border px-3 py-2.5 text-xs"/></div><footer className="flex justify-end border-t px-6 py-4"><button className="rounded-xl bg-indigo-600 px-5 py-2 text-xs font-bold text-white">保存</button></footer></form></div>}
    {joining && <div className="fixed inset-0 z-[130] flex items-center justify-center bg-slate-900/40 p-4"><div className="w-full max-w-md overflow-hidden rounded-2xl bg-white"><header className="border-b px-6 py-4"><h3 className="font-black">拉入当前组织 · {joining.displayName}</h3><p className="text-xs text-slate-400">加入后不能再归属其他组织</p></header><div className="p-6"><select value={roleCode} onChange={(e) => setRoleCode(e.target.value)} className="w-full rounded-xl border px-3 py-2.5 text-xs">{availableRoles.map((role) => <option key={role.id} value={role.code}>{role.name}</option>)}</select></div><footer className="flex justify-end gap-2 border-t px-6 py-4"><button onClick={() => setJoining(null)} className="rounded-xl border px-4 py-2 text-xs">取消</button><button onClick={() => void join()} className="rounded-xl bg-indigo-600 px-5 py-2 text-xs font-bold text-white">确认加入</button></footer></div></div>}
  </section>;
}
