import { FormEvent, ReactNode, useCallback, useEffect, useState } from "react";
import { KeyRound, Pencil, Plus, Search, Trash2, X } from "lucide-react";
import { apiRequest } from "../api/httpClient";

interface RegisteredUser {
  id: string; username: string; displayName: string; email: string; feishuUserId: string | null;
  status: "ACTIVE" | "SUSPENDED" | "DEACTIVATED"; isSystemAdmin: boolean; version: number;
  organizationMembers: Array<{ organization: { id: string; name: string } }>;
}

function Dialog({ title, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) {
  return <div className="fixed inset-0 z-[130] flex items-center justify-center bg-slate-900/35 p-4"><div className="w-full max-w-2xl overflow-hidden rounded-2xl bg-white shadow-2xl"><header className="flex items-center justify-between px-6 py-4"><h3 className="font-black">{title}</h3><button onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X className="h-4 w-4"/></button></header>{children}</div></div>;
}

export default function SystemUserRegistry({ currentUserId }: { currentUserId: string }) {
  const [users, setUsers] = useState<RegisteredUser[]>([]);
  const [query, setQuery] = useState("");
  const [message, setMessage] = useState("");
  const [saving, setSaving] = useState(false);
  const [creating, setCreating] = useState(false);
  const [editing, setEditing] = useState<RegisteredUser | null>(null);
  const [resetting, setResetting] = useState<RegisteredUser | null>(null);
  const [password, setPassword] = useState("");
  const [form, setForm] = useState({ username: "", displayName: "", email: "", password: "", feishuUserId: "" });
  const [editForm, setEditForm] = useState({ displayName: "", email: "", feishuUserId: "" });
  const load = useCallback(async () => { const params = new URLSearchParams({ limit: "100" }); if (query.trim()) params.set("q", query.trim()); const result = await apiRequest<{ items: RegisteredUser[] }>(`/users?${params}`); setUsers(result.items); }, [query]);
  useEffect(() => { const timer = setTimeout(() => void load().catch((error) => setMessage(error instanceof Error ? error.message : "账号加载失败")), 200); return () => clearTimeout(timer); }, [load]);

  const create = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { await apiRequest("/users", { method: "POST", body: JSON.stringify({ ...form, feishuUserId: form.feishuUserId || undefined }) }); setCreating(false); setForm({ username: "", displayName: "", email: "", password: "", feishuUserId: "" }); await load(); setMessage("账号已创建"); } catch (error) { setMessage(error instanceof Error ? error.message : "创建失败"); } finally { setSaving(false); } };
  const saveEdit = async (event: FormEvent) => { event.preventDefault(); if (!editing) return; setSaving(true); try { await apiRequest(`/users/${editing.id}`, { method: "PATCH", body: JSON.stringify({ version: editing.version, ...editForm }) }); setEditing(null); await load(); setMessage("账号资料已更新"); } catch (error) { setMessage(error instanceof Error ? error.message : "保存失败"); } finally { setSaving(false); } };
  const resetPassword = async (event: FormEvent) => { event.preventDefault(); if (!resetting) return; setSaving(true); try { await apiRequest(`/users/${resetting.id}/password`, { method: "PUT", body: JSON.stringify({ password }) }); setResetting(null); setPassword(""); setMessage("密码已重置，原登录会话已失效"); } catch (error) { setMessage(error instanceof Error ? error.message : "重置失败"); } finally { setSaving(false); } };
  const remove = async (user: RegisteredUser) => { if (!window.confirm(`确认删除账号 @${user.username}？`)) return; try { await apiRequest(`/users/${user.id}`, { method: "DELETE" }); await load(); setMessage("账号已删除"); } catch (error) { setMessage(error instanceof Error ? error.message : "删除失败"); } };
  const toggle = async (user: RegisteredUser) => { setSaving(true); try { await apiRequest(`/users/${user.id}`, { method: "PATCH", body: JSON.stringify({ version: user.version, status: user.status === "ACTIVE" ? "DEACTIVATED" : "ACTIVE" }) }); await load(); } finally { setSaving(false); } };

  return <section className="overflow-hidden rounded-2xl bg-white shadow-sm">
    <div className="flex justify-end gap-2 px-5 py-4"><label className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索用户名、账号或邮箱" className="w-64 rounded-xl bg-slate-50 py-2.5 pl-9 pr-3 text-xs outline-none focus:ring-2 focus:ring-indigo-200"/></label><button onClick={() => setCreating(true)} className="inline-flex items-center gap-1 rounded-xl bg-slate-900 px-4 py-2 text-xs font-bold text-white"><Plus className="h-4 w-4"/>添加账号</button></div>
    {message && <div className="mx-5 mb-3 rounded-xl bg-indigo-50 px-4 py-2.5 text-xs text-indigo-700">{message}</div>}
    <div className="overflow-auto"><table className="w-full min-w-[980px] text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-5 py-3">用户名</th><th>账号</th><th>邮箱</th><th>角色</th><th>所属组织</th><th>状态</th><th className="pr-5 text-right">操作</th></tr></thead><tbody className="divide-y divide-slate-100">{users.map((user) => <tr key={user.id} className="hover:bg-slate-50/70"><td className="px-5 py-4 font-bold">{user.displayName}</td><td className="font-mono text-slate-500">@{user.username}</td><td className="text-slate-500">{user.email || "—"}</td><td><span className={user.isSystemAdmin ? "rounded-md bg-violet-50 px-2 py-1 text-violet-700" : "rounded-md bg-slate-100 px-2 py-1 text-slate-600"}>{user.isSystemAdmin ? "系统管理员" : "普通用户"}</span></td><td>{user.organizationMembers[0]?.organization.name || "未归属"}</td><td><button disabled={user.id === currentUserId} onClick={() => void toggle(user)} className={user.status === "ACTIVE" ? "text-emerald-600" : "text-rose-600"}>{user.status === "ACTIVE" ? "启用" : "禁用"}</button></td><td className="pr-5 text-right"><button onClick={() => { setEditing(user); setEditForm({ displayName: user.displayName, email: user.email, feishuUserId: user.feishuUserId || "" }); }} className="inline-flex items-center gap-1 font-bold text-indigo-600"><Pencil className="h-3.5 w-3.5"/>编辑</button><button onClick={() => { setResetting(user); setPassword(""); }} className="ml-4 inline-flex items-center gap-1 font-bold text-amber-600"><KeyRound className="h-3.5 w-3.5"/>重置密码</button>{!user.isSystemAdmin && <button onClick={() => void remove(user)} className="ml-4 inline-flex items-center gap-1 font-bold text-rose-600"><Trash2 className="h-3.5 w-3.5"/>删除</button>}</td></tr>)}</tbody></table></div>
    {creating && <Dialog title="添加账号" onClose={() => setCreating(false)}><form onSubmit={create}><div className="grid gap-3 bg-slate-50/60 p-6 md:grid-cols-2">{([ ["username", "登录账号"], ["displayName", "用户名"], ["email", "联系邮箱"], ["password", "初始密码（至少12位）"], ["feishuUserId", "飞书 User ID（可选）"] ] as const).map(([key, placeholder]) => <input key={key} required={key !== "feishuUserId"} type={key === "password" ? "password" : key === "email" ? "email" : "text"} minLength={key === "password" ? 12 : undefined} value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} placeholder={placeholder} className="rounded-xl bg-white px-3 py-2.5 text-xs outline-none shadow-sm"/>)}</div><footer className="flex justify-end gap-2 px-6 py-4"><button type="button" onClick={() => setCreating(false)} className="rounded-xl bg-slate-100 px-4 py-2 text-xs">取消</button><button disabled={saving} className="rounded-xl bg-indigo-600 px-5 py-2 text-xs font-bold text-white">创建账号</button></footer></form></Dialog>}
    {editing && <Dialog title={`编辑账号 · @${editing.username}`} onClose={() => setEditing(null)}><form onSubmit={saveEdit}><div className="grid gap-3 bg-slate-50/60 p-6"><input value={editForm.displayName} onChange={(event) => setEditForm({ ...editForm, displayName: event.target.value })} placeholder="用户名" className="rounded-xl bg-white px-3 py-2.5 text-xs outline-none shadow-sm"/><input type="email" value={editForm.email} onChange={(event) => setEditForm({ ...editForm, email: event.target.value })} placeholder="邮箱" className="rounded-xl bg-white px-3 py-2.5 text-xs outline-none shadow-sm"/><input value={editForm.feishuUserId} onChange={(event) => setEditForm({ ...editForm, feishuUserId: event.target.value })} placeholder="飞书 User ID" className="rounded-xl bg-white px-3 py-2.5 text-xs outline-none shadow-sm"/></div><footer className="flex justify-end gap-2 px-6 py-4"><button type="button" onClick={() => setEditing(null)} className="rounded-xl bg-slate-100 px-4 py-2 text-xs">取消</button><button className="rounded-xl bg-indigo-600 px-5 py-2 text-xs font-bold text-white">保存</button></footer></form></Dialog>}
    {resetting && <Dialog title={`重置密码 · @${resetting.username}`} onClose={() => setResetting(null)}><form onSubmit={resetPassword}><div className="bg-slate-50/60 p-6"><input autoFocus required type="password" minLength={12} value={password} onChange={(event) => setPassword(event.target.value)} placeholder="输入至少 12 位新密码" className="w-full rounded-xl bg-white px-3 py-2.5 text-xs outline-none shadow-sm"/></div><footer className="flex justify-end gap-2 px-6 py-4"><button type="button" onClick={() => setResetting(null)} className="rounded-xl bg-slate-100 px-4 py-2 text-xs">取消</button><button disabled={saving} className="rounded-xl bg-amber-600 px-5 py-2 text-xs font-bold text-white">确认重置</button></footer></form></Dialog>}
  </section>;
}
