import Joi from "joi";

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string().valid("development", "test", "production").default("development"),
  PORT: Joi.number().port().default(3001),
  API_PREFIX: Joi.string().default("api"),
  LOG_LEVEL: Joi.string().valid("fatal", "error", "warn", "log", "debug", "verbose").default("log"),
  TRUST_PROXY: Joi.boolean().default(false),
  CORS_ORIGINS: Joi.string().default("http://localhost:5173"),
  DATABASE_URL: Joi.string().uri({ scheme: ["postgresql"] }).required(),
  REDIS_URL: Joi.string().uri({ scheme: ["redis", "rediss"] }).required(),
  JWT_ACCESS_SECRET: Joi.string().min(32).required(),
  JWT_REFRESH_SECRET: Joi.string().min(32).required(),
  JWT_ACCESS_TTL: Joi.string().default("15m"),
  JWT_REFRESH_TTL: Joi.string().default("7d"),
  JWT_ISSUER: Joi.string().default("veritab-api"),
  JWT_AUDIENCE: Joi.string().default("veritab-web"),
  COOKIE_SECURE: Joi.boolean().default(false),
  COOKIE_DOMAIN: Joi.string().allow("").optional(),
  AI_BASE_URL: Joi.string().uri({ scheme: ["https", "http"] }).allow("").optional(),
  AI_API_KEY: Joi.string().min(8).allow("").optional(),
  AI_MODEL: Joi.string().max(160).allow("").optional(),
  AI_TIMEOUT_MS: Joi.number().integer().min(1000).max(120000).default(30000),
  WEBHOOK_ENCRYPTION_KEY: Joi.string().base64().optional(),
  S3_ENDPOINT: Joi.string().uri({ scheme: ["https", "http"] }).allow("").optional(),
  S3_REGION: Joi.string().default("us-east-1"),
  S3_BUCKET: Joi.string().max(255).allow("").optional(),
  S3_ACCESS_KEY_ID: Joi.string().allow("").optional(),
  S3_SECRET_ACCESS_KEY: Joi.string().allow("").optional(),
  S3_FORCE_PATH_STYLE: Joi.boolean().default(false),
  S3_UPLOAD_URL_TTL: Joi.number().integer().min(60).max(3600).default(600),
  S3_DOWNLOAD_URL_TTL: Joi.number().integer().min(30).max(3600).default(300),
  FILE_MAX_SIZE_BYTES: Joi.number().integer().min(1).max(104857600).default(10485760),
  FILE_PENDING_RETENTION_HOURS: Joi.number().integer().min(1).max(168).default(24),
}).and("S3_ACCESS_KEY_ID", "S3_SECRET_ACCESS_KEY");
