import { ReactNode, useMemo, useState } from "react";
import { Pencil, Plus, Trash2, X } from "lucide-react";
import { useMembers } from "../../features/members/api/useMembers";
import { ApiRole, MemberApiScope } from "../../features/members/api/types";

const labels: Record<string, string> = { organization: "组织", member: "成员", space: "项目空间" };
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) { return <div className="fixed inset-0 z-[120] flex items-center justify-center bg-slate-900/40 p-4 backdrop-blur-xs"><div className="flex max-h-[90vh] w-full max-w-3xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl"><header className="flex items-center justify-between border-b border-slate-100 px-6 py-4"><h3 className="font-black text-slate-900">{title}</h3><button onClick={onClose}><X className="h-4 w-4 text-slate-400"/></button></header>{children}</div></div>; }
export default function OrganizationRoleManagement({ scope }: { scope: MemberApiScope }) {
  const remote = useMembers(scope); const [editor, setEditor] = useState<ApiRole | "new" | null>(null); const [draft, setDraft] = useState({ name: "", description: "", permissionCodes: [] as string[] }); const [message, setMessage] = useState("");
  const permissions = useMemo(() => remote.permissions.filter((item) => item.code.startsWith("organization.") || item.code.startsWith("member.") || item.code === "space.manage"), [remote.permissions]);
  const grouped = useMemo(() => Object.entries(permissions.reduce<Record<string, typeof permissions>>((all, item) => { (all[item.code.split(".")[0]] ||= []).push(item); return all; }, {})), [permissions]);
  const open = (role: ApiRole | "new") => { setEditor(role); setDraft(role === "new" ? { name: "", description: "", permissionCodes: [] } : { name: role.name, description: role.description || "", permissionCodes: role.permissions.map((item) => item.permission.code) }); };
  const run = async (action: () => Promise<unknown>, success: string) => { try { await action(); setMessage(success); } catch (error) { setMessage(error instanceof Error ? error.message : "操作失败"); } };
  const save = async () => { if (!editor) return; await run(() => editor === "new" ? remote.createRole(draft) : remote.updateRole({ roleId: editor.id, version: editor.version, ...draft }), "组织角色已保存"); setEditor(null); };
  return <section className="overflow-hidden rounded-2xl bg-white shadow-sm"><div className="flex items-center justify-between px-5 py-4"><div><h3 className="text-sm font-black">组织全局角色</h3><p className="mt-1 text-[11px] text-slate-400">作用于当前组织，权限仅包含组织、成员和项目创建</p></div><button onClick={() => open("new")} className="inline-flex items-center gap-1 rounded-xl bg-slate-900 px-4 py-2 text-xs font-bold text-white"><Plus className="h-4 w-4"/>新建组织角色</button></div>{message && <div className="mx-5 mb-3 rounded-lg bg-indigo-50 px-3 py-2 text-xs text-indigo-700">{message}</div>}<table className="w-full text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-5 py-3">角色</th><th>生效范围</th><th>权限</th><th className="pr-5 text-right">操作</th></tr></thead><tbody className="divide-y divide-slate-100">{remote.roles.map((role) => <tr key={role.id}><td className="px-5 py-4 font-bold">{role.name}</td><td><span className="rounded-md bg-violet-50 px-2 py-1 text-[10px] text-violet-700">组织全局</span></td><td>{role.permissions.length} 项</td><td className="pr-5 text-right"><button onClick={() => open(role)} className="inline-flex items-center gap-1 font-bold text-indigo-600"><Pencil className="h-3.5 w-3.5"/>{role.isSystem ? "查看" : "编辑"}</button>{!role.isSystem && <button onClick={() => void run(() => remote.deleteRole(role.id), "角色已删除")} className="ml-4 inline-flex items-center gap-1 font-bold text-rose-600"><Trash2 className="h-3.5 w-3.5"/>删除</button>}</td></tr>)}</tbody></table>
    {editor && <Modal title={editor === "new" ? "新建组织全局角色" : editor.name} onClose={() => setEditor(null)}><div className="overflow-y-auto p-6"><div className="grid gap-3 md:grid-cols-2"><input disabled={editor !== "new" && editor.isSystem} value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} placeholder="角色名称" className="rounded-xl border border-slate-200 px-3 py-2.5 text-xs disabled:bg-slate-50"/><input disabled={editor !== "new" && editor.isSystem} value={draft.description} onChange={(e) => setDraft({ ...draft, description: e.target.value })} placeholder="角色说明" className="rounded-xl border border-slate-200 px-3 py-2.5 text-xs disabled:bg-slate-50"/></div><div className="mt-4 space-y-3">{grouped.map(([module, items]) => <fieldset key={module} className="rounded-xl bg-slate-50 p-4"><legend className="px-2 text-xs font-black">{labels[module] || module}</legend><div className="grid gap-2 sm:grid-cols-2">{items.map((item) => <label key={item.code} className="flex gap-2 text-xs"><input disabled={editor !== "new" && editor.isSystem} type="checkbox" checked={draft.permissionCodes.includes(item.code)} onChange={(e) => setDraft({ ...draft, permissionCodes: e.target.checked ? [...draft.permissionCodes, item.code] : draft.permissionCodes.filter((code) => code !== item.code) })}/>{item.description}</label>)}</div></fieldset>)}</div></div><footer className="flex justify-end gap-2 border-t border-slate-100 px-6 py-4"><button onClick={() => setEditor(null)} className="rounded-xl bg-slate-100 px-4 py-2 text-xs">关闭</button>{(editor === "new" || !editor.isSystem) && <button onClick={() => void save()} className="rounded-xl bg-indigo-600 px-5 py-2 text-xs font-bold text-white">保存</button>}</footer></Modal>}
  </section>;
}
