import { ReactNode, useCallback, useEffect, useMemo, useState } from "react";
import { Plus, X } from "lucide-react";
import { apiRequest } from "../../api/httpClient";
import { ApiPermission, ApiRole } from "../../features/members/api/types";
const labels: Record<string, string> = { space: "项目空间", member: "成员", requirement: "需求", defect: "缺陷", testcase: "用例", integration: "服务集成", audit: "审计" };
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) { return <div className="fixed inset-0 z-[120] flex items-center justify-center bg-slate-900/40 p-4"><div className="flex max-h-[90vh] w-full max-w-3xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl"><header className="flex justify-between border-b border-slate-100 px-6 py-4"><h3 className="font-black">{title}</h3><button onClick={onClose}><X className="h-4 w-4"/></button></header>{children}</div></div>; }
export default function ProjectRoleManagement({ organizationId, project }: { organizationId: string; project: { id: string; name: string } }) {
  const root = `/organizations/${organizationId}/spaces/${project.id}`; const [roles, setRoles] = useState<ApiRole[]>([]); const [permissions, setPermissions] = useState<ApiPermission[]>([]); const [editor, setEditor] = useState<ApiRole | "new" | null>(null); const [draft, setDraft] = useState({ name: "", description: "", permissionCodes: [] as string[] });
  const load = useCallback(async () => { const [roleRows, permissionRows] = await Promise.all([apiRequest<ApiRole[]>(`${root}/roles`), apiRequest<ApiPermission[]>(`/organizations/${organizationId}/permissions`)]); setRoles(roleRows.filter((role) => role.scope === "PROJECT_SPACE" && role.projectSpaceId === project.id)); setPermissions(permissionRows.filter((item) => !item.code.startsWith("organization."))); }, [organizationId, project.id, root]); useEffect(() => { void load(); }, [load]);
  const grouped = useMemo(() => Object.entries(permissions.reduce<Record<string, ApiPermission[]>>((all, item) => { (all[item.code.split(".")[0]] ||= []).push(item); return all; }, {})), [permissions]); const open = (role: ApiRole | "new") => { setEditor(role); setDraft(role === "new" ? { name: "", description: "", permissionCodes: [] } : { name: role.name, description: role.description || "", permissionCodes: role.permissions.map((item) => item.permission.code) }); };
  const save = async () => { if (!editor) return; await apiRequest(editor === "new" ? `${root}/roles` : `${root}/roles/${editor.id}`, { method: editor === "new" ? "POST" : "PATCH", body: JSON.stringify({ ...draft, ...(editor === "new" ? {} : { version: editor.version }) }) }); await load(); setEditor(null); };
  return <section className="overflow-hidden rounded-2xl bg-white shadow-sm"><div className="flex items-center justify-between px-5 py-3"><div><h3 className="text-sm font-black">项目私有角色</h3><p className="mt-0.5 text-[11px] text-slate-400">仅在当前项目空间内可见并生效</p></div><button onClick={() => open("new")} className="inline-flex items-center gap-1 rounded-xl bg-slate-900 px-4 py-2 text-xs font-bold text-white"><Plus className="h-4 w-4"/>新建私有角色</button></div><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-5 py-3">角色</th><th>生效范围</th><th>权限</th><th className="pr-5 text-right">操作</th></tr></thead><tbody>{roles.map((role) => <tr key={role.id}><td className="px-5 py-4 font-bold">{role.name}</td><td><span className="rounded-md bg-sky-50 px-2 py-1 text-[10px] text-sky-700">仅当前项目</span></td><td>{role.permissions.length} 项</td><td className="pr-5 text-right"><button onClick={() => open(role)} className="font-bold text-indigo-600">编辑</button></td></tr>)}</tbody></table>{!roles.length && <div className="py-10 text-center text-xs text-slate-400">暂无项目私有角色</div>}
    {editor && <Modal title={editor === "new" ? "新建项目私有角色" : editor.name} onClose={() => setEditor(null)}><div className="overflow-y-auto p-6"><div className="grid gap-3 md:grid-cols-2"><input value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} placeholder="角色名称" className="rounded-xl border border-slate-200 px-3 py-2.5 text-xs"/><input value={draft.description} onChange={(e) => setDraft({ ...draft, description: e.target.value })} placeholder="角色说明" className="rounded-xl border border-slate-200 px-3 py-2.5 text-xs"/></div><div className="mt-4 space-y-3">{grouped.map(([module, items]) => <fieldset key={module} className="rounded-xl bg-slate-50 p-4"><legend className="px-2 text-xs font-black">{labels[module] || module}</legend><div className="grid gap-2 sm:grid-cols-2 md:grid-cols-3">{items.map((item) => <label key={item.code} className="flex gap-2 text-xs"><input type="checkbox" checked={draft.permissionCodes.includes(item.code)} onChange={(e) => setDraft({ ...draft, permissionCodes: e.target.checked ? [...draft.permissionCodes, item.code] : draft.permissionCodes.filter((code) => code !== item.code) })}/>{item.description}</label>)}</div></fieldset>)}</div></div><footer className="flex justify-end gap-2 border-t border-slate-100 px-6 py-4"><button onClick={() => setEditor(null)} className="rounded-xl bg-slate-100 px-4 py-2 text-xs">取消</button><button onClick={() => void save()} className="rounded-xl bg-indigo-600 px-5 py-2 text-xs font-bold text-white">保存</button></footer></Modal>}
  </section>;
}
