import { ReactNode, useCallback, useEffect, useMemo, useState } from "react";
import { X } from "lucide-react";
import { apiRequest } from "../../api/httpClient";
import { ApiPermission, ApiRole } from "../../features/members/api/types";
import TenantListLayout from "./TenantListLayout";
const labels: Record<string, string> = { space: "项目空间", member: "成员", requirement: "需求", defect: "缺陷", testcase: "用例", integration: "服务集成", audit: "审计" };
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) { return <div className="fixed inset-0 z-[120] flex items-center justify-center bg-slate-900/35 p-4"><div className="flex max-h-[90vh] w-full max-w-3xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl"><header className="flex justify-between px-6 py-4"><h3 className="font-black">{title}</h3><button onClick={onClose}><X className="h-4 w-4"/></button></header>{children}</div></div>; }
export default function ProjectRoleManagement({ organizationId, project, onAddUser }: { organizationId: string; project: { id: string; name: string }; onAddUser: () => void }) {
  const root = `/organizations/${organizationId}/spaces/${project.id}`; const [roles, setRoles] = useState<ApiRole[]>([]); const [administrator, setAdministrator] = useState<ApiRole | null>(null); const [permissions, setPermissions] = useState<ApiPermission[]>([]); const [editor, setEditor] = useState<ApiRole | "new" | null>(null); const [draft, setDraft] = useState({ name: "", description: "", permissionCodes: [] as string[] });
  const [query, setQuery] = useState(""); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(10);
  const load = useCallback(async () => { const [roleRows, organizationRoles, permissionRows] = await Promise.all([apiRequest<ApiRole[]>(`${root}/roles`), apiRequest<ApiRole[]>(`/organizations/${organizationId}/roles`), apiRequest<ApiPermission[]>(`/organizations/${organizationId}/permissions`)]); setRoles(roleRows.filter((role) => role.scope === "PROJECT_SPACE" && role.projectSpaceId === project.id)); setAdministrator(organizationRoles.find((role) => role.code === "org_admin") || null); setPermissions(permissionRows.filter((item) => !item.code.startsWith("organization."))); }, [organizationId, project.id, root]); useEffect(() => { void load(); }, [load]);
  const grouped = useMemo(() => Object.entries(permissions.reduce<Record<string, ApiPermission[]>>((all, item) => { (all[item.code.split(".")[0]] ||= []).push(item); return all; }, {})), [permissions]); const open = (role: ApiRole | "new") => { setEditor(role); setDraft(role === "new" ? { name: "", description: "", permissionCodes: [] } : { name: role.name, description: role.description || "", permissionCodes: role.permissions.map((item) => item.permission.code) }); };
  const save = async () => { if (!editor) return; await apiRequest(editor === "new" ? `${root}/roles` : `${root}/roles/${editor.id}`, { method: editor === "new" ? "POST" : "PATCH", body: JSON.stringify({ ...draft, ...(editor === "new" ? {} : { version: editor.version }) }) }); await load(); setEditor(null); };
  const normalizedQuery = query.trim().toLowerCase();
  const filteredRoles = roles.filter((role) => role.name.toLowerCase().includes(normalizedQuery));
  const showAdministrator = Boolean(administrator && "系统管理员".includes(query.trim()));
  const allRows: Array<{ kind: "administrator" | "private"; role: ApiRole }> = [
    ...(showAdministrator && administrator ? [{ kind: "administrator" as const, role: administrator }] : []),
    ...filteredRoles.map((role) => ({ kind: "private" as const, role })),
  ];
  const visibleRoles = allRows.slice((page - 1) * pageSize, page * pageSize);
  return <TenantListLayout title="角色列表" total={allRows.length} query={query} onQueryChange={(value) => { setQuery(value); setPage(1); }} searchPlaceholder="搜索角色名称..." actionLabel="新建私有角色" onAction={() => open("new")} secondaryActionLabel="添加管理员" onSecondaryAction={onAddUser} page={page} pageSize={pageSize} onPageChange={setPage} onPageSizeChange={(size) => { setPageSize(size); setPage(1); }}><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-5 py-3">角色名称</th><th>角色类型</th><th>生效范围</th><th>权限</th><th className="pr-5 text-right">操作</th></tr></thead><tbody className="divide-y divide-slate-100">{visibleRoles.map(({ kind, role }) => kind === "administrator" ? <tr key={role.id}><td className="px-5 py-4 font-bold">系统管理员</td><td><span className="rounded-md bg-violet-50 px-2 py-1 text-violet-700">系统内置</span></td><td>组织全局</td><td>{role.permissions.length} 项</td><td className="pr-5 text-right text-slate-400">固定角色</td></tr> : <tr key={role.id}><td className="px-5 py-4 font-bold">{role.name}</td><td><span className="rounded-md bg-sky-50 px-2 py-1 text-sky-700">项目私有</span></td><td>仅当前项目</td><td>{role.permissions.length} 项</td><td className="pr-5 text-right"><button onClick={() => open(role)} className="font-bold text-indigo-600">编辑</button></td></tr>)}</tbody></table>
    {editor && <Modal title={editor === "new" ? "新建项目私有角色" : editor.name} onClose={() => setEditor(null)}><div className="overflow-y-auto bg-slate-50/60 p-6"><div className="grid gap-3 md:grid-cols-2"><input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} placeholder="角色名称" className="rounded-xl bg-white px-3 py-2.5 text-xs outline-none shadow-sm"/><input value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} placeholder="角色说明" className="rounded-xl bg-white px-3 py-2.5 text-xs outline-none shadow-sm"/></div><div className="mt-4 space-y-3">{grouped.map(([module, items]) => <fieldset key={module} className="rounded-xl bg-white p-4 shadow-sm"><legend className="px-2 text-xs font-black">{labels[module] || module}</legend><div className="grid gap-2 sm:grid-cols-2 md:grid-cols-3">{items.map((item) => <label key={item.code} className="flex gap-2 text-xs"><input type="checkbox" checked={draft.permissionCodes.includes(item.code)} onChange={(event) => setDraft({ ...draft, permissionCodes: event.target.checked ? [...draft.permissionCodes, item.code] : draft.permissionCodes.filter((code) => code !== item.code) })}/>{item.description}</label>)}</div></fieldset>)}</div></div><footer className="flex justify-end gap-2 px-6 py-4"><button onClick={() => setEditor(null)} className="rounded-xl bg-slate-100 px-4 py-2 text-xs">取消</button><button onClick={() => void save()} className="rounded-xl bg-indigo-600 px-5 py-2 text-xs font-bold text-white">保存</button></footer></Modal>}
  </TenantListLayout>;
}
