import { ReactNode, useCallback, useEffect, useState } from "react";
import { UserPlus, X } from "lucide-react";
import { apiRequest } from "../../api/httpClient";
import { ApiOrganizationMember, ApiRole } from "../../features/members/api/types";
interface Member { status: "ACTIVE" | "SUSPENDED"; user: { id: string; username: string; displayName: string; roleBindings: Array<{ role: Pick<ApiRole, "id" | "name" | "scope" | "projectSpaceId"> }> } }
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) { return <div className="fixed inset-0 z-[120] flex items-center justify-center bg-slate-900/40 p-4"><div className="w-full max-w-2xl overflow-hidden rounded-2xl bg-white shadow-2xl"><header className="flex justify-between border-b border-slate-100 px-6 py-4"><h3 className="font-black">{title}</h3><button onClick={onClose}><X className="h-4 w-4"/></button></header>{children}</div></div>; }
export default function ProjectMemberManagement({ organizationId, project, currentUserId }: { organizationId: string; project: { id: string; name: string }; currentUserId: string }) {
  const root = `/organizations/${organizationId}/spaces/${project.id}`; const [members, setMembers] = useState<Member[]>([]); const [pool, setPool] = useState<ApiOrganizationMember[]>([]); const [roles, setRoles] = useState<ApiRole[]>([]); const [editor, setEditor] = useState<Member | "add" | null>(null); const [userId, setUserId] = useState(""); const [roleIds, setRoleIds] = useState<string[]>([]); const [message, setMessage] = useState("");
  const load = useCallback(async () => { const [memberRows, poolRows, roleRows] = await Promise.all([apiRequest<Member[]>(`${root}/members`), apiRequest<ApiOrganizationMember[]>(`/organizations/${organizationId}/members`), apiRequest<ApiRole[]>(`${root}/roles`)]); setMembers(memberRows); setPool(poolRows); setRoles(roleRows); }, [organizationId, root]); useEffect(() => { void load(); }, [load]);
  const run = async (action: () => Promise<unknown>, success: string) => { try { await action(); await load(); setMessage(success); } catch (error) { setMessage(error instanceof Error ? error.message : "操作失败"); } };
  const save = async () => { if (!editor || editor === "add") return; await run(() => apiRequest(`${root}/members/${editor.user.id}/roles`, { method: "PUT", body: JSON.stringify({ roleIds }) }), "空间角色已更新"); setEditor(null); };
  const add = async () => { if (!userId) return; await run(() => apiRequest(`${root}/members`, { method: "POST", body: JSON.stringify({ userId }) }), "成员已加入项目空间"); setEditor(null); setUserId(""); };
  return <section className="overflow-hidden rounded-2xl bg-white shadow-sm"><div className="flex items-center justify-between px-5 py-4"><div><h3 className="text-sm font-black">{project.name} · 空间成员</h3><p className="mt-1 text-[11px] text-slate-400">仅展示已加入本项目的组织成员，支持叠加多个角色</p></div><button onClick={() => setEditor("add")} className="inline-flex items-center gap-1 rounded-xl bg-slate-900 px-4 py-2 text-xs font-bold text-white"><UserPlus className="h-4 w-4"/>添加成员</button></div>{message && <div className="mx-5 mb-3 rounded-lg bg-indigo-50 px-3 py-2 text-xs text-indigo-700">{message}</div>}<table className="w-full text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-5 py-3">成员</th><th>空间角色</th><th>状态</th><th className="pr-5 text-right">操作</th></tr></thead><tbody className="divide-y divide-slate-100">{members.map((member) => <tr key={member.user.id}><td className="px-5 py-4 font-bold">{member.user.displayName}<div className="font-mono text-[10px] font-normal text-slate-400">@{member.user.username}</div></td><td>{member.user.roleBindings.map((item) => item.role.name).join("、") || "未分配"}</td><td className="text-emerald-600">正常</td><td className="pr-5 text-right"><button onClick={() => { setEditor(member); setRoleIds(member.user.roleBindings.map((item) => item.role.id)); }} className="font-bold text-indigo-600">编辑角色</button>{member.user.id !== currentUserId && <button onClick={() => void run(() => apiRequest(`${root}/members/${member.user.id}`, { method: "DELETE" }), "成员已移出项目")} className="ml-4 font-bold text-rose-600">移出</button>}</td></tr>)}</tbody></table>
    {editor === "add" && <Modal title="从组织成员池添加" onClose={() => setEditor(null)}><div className="p-6"><select value={userId} onChange={(e) => setUserId(e.target.value)} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-xs"><option value="">选择成员</option>{pool.filter((item) => !members.some((member) => member.user.id === item.user.id)).map((item) => <option key={item.user.id} value={item.user.id}>{item.user.displayName} (@{item.user.username})</option>)}</select></div><footer className="flex justify-end gap-2 border-t border-slate-100 px-6 py-4"><button onClick={() => setEditor(null)} className="rounded-xl bg-slate-100 px-4 py-2 text-xs">取消</button><button onClick={() => void add()} className="rounded-xl bg-indigo-600 px-5 py-2 text-xs font-bold text-white">确认添加</button></footer></Modal>}
    {editor && editor !== "add" && <Modal title={`编辑空间角色 · ${editor.user.displayName}`} onClose={() => setEditor(null)}><div className="grid gap-2 p-6 sm:grid-cols-2">{roles.map((role) => <label key={role.id} className="flex gap-2 rounded-xl bg-slate-50 p-3 text-xs"><input type="checkbox" checked={roleIds.includes(role.id)} onChange={(e) => setRoleIds(e.target.checked ? [...roleIds, role.id] : roleIds.filter((id) => id !== role.id))}/>{role.name}<span className="text-slate-400">{role.scope === "ORGANIZATION" ? "组织全局" : role.projectSpaceId ? "项目私有" : "系统"}</span></label>)}</div><footer className="flex justify-end gap-2 border-t border-slate-100 px-6 py-4"><button onClick={() => setEditor(null)} className="rounded-xl bg-slate-100 px-4 py-2 text-xs">取消</button><button onClick={() => void save()} className="rounded-xl bg-indigo-600 px-5 py-2 text-xs font-bold text-white">保存</button></footer></Modal>}
  </section>;
}
