import { ChevronLeft, ChevronRight, Plus, Search } from "lucide-react";
import { ReactNode } from "react";

export default function TenantListLayout({ title, total, query, onQueryChange, searchPlaceholder, actionLabel, onAction, secondaryActionLabel, onSecondaryAction, page, pageSize, onPageChange, onPageSizeChange, children }: {
  title: string; total: number; query: string; onQueryChange: (value: string) => void; searchPlaceholder: string;
  actionLabel: string; onAction: () => void; secondaryActionLabel?: string; onSecondaryAction?: () => void; page: number; pageSize: number; onPageChange: (page: number) => void; onPageSizeChange: (size: number) => void; children: ReactNode;
}) {
  const pages = Math.max(1, Math.ceil(total / pageSize));
  return <section className="overflow-hidden rounded-2xl bg-white shadow-sm">
    <header className="flex items-center gap-2 px-5 py-4"><h2 className="text-sm font-black text-slate-800">{title}</h2><span className="rounded-full bg-slate-100 px-2 py-0.5 text-[10px] font-bold text-slate-500">{page} / {pages}</span></header>
    <div className="mx-5 mb-4 flex items-center gap-3 rounded-2xl bg-slate-50/80 p-3"><label className="relative flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><input value={query} onChange={(event) => onQueryChange(event.target.value)} placeholder={searchPlaceholder} className="w-full rounded-xl bg-white py-2.5 pl-9 pr-3 text-xs outline-none shadow-sm focus:ring-2 focus:ring-indigo-200"/></label>{secondaryActionLabel && <button onClick={onSecondaryAction} className="rounded-xl bg-white px-4 py-2.5 text-xs font-bold text-slate-700 shadow-sm">{secondaryActionLabel}</button>}<button onClick={onAction} className="inline-flex items-center gap-1 rounded-xl bg-indigo-600 px-4 py-2.5 text-xs font-bold text-white shadow-sm hover:bg-indigo-700"><Plus className="h-4 w-4"/>{actionLabel}</button></div>
    <div className="overflow-auto">{children}</div>
    <footer className="flex items-center justify-between px-5 py-4 text-xs"><div className="flex items-center gap-4"><strong className="text-slate-600">共 {total} 条数据</strong><label className="flex items-center gap-2 text-slate-400">单页显示：<select value={pageSize} onChange={(event) => onPageSizeChange(Number(event.target.value))} className="rounded-lg bg-slate-50 px-2.5 py-2 font-bold text-slate-700 outline-none"><option value={10}>10 条/页</option><option value={20}>20 条/页</option><option value={50}>50 条/页</option></select></label></div><div className="flex items-center gap-2"><button disabled={page <= 1} onClick={() => onPageChange(page - 1)} className="rounded-lg bg-slate-50 p-2 text-slate-400 disabled:opacity-40"><ChevronLeft className="h-4 w-4"/></button><span className="rounded-lg bg-indigo-600 px-3 py-2 font-bold text-white">{page}</span><button disabled={page >= pages} onClick={() => onPageChange(page + 1)} className="rounded-lg bg-slate-50 p-2 text-slate-400 disabled:opacity-40"><ChevronRight className="h-4 w-4"/></button></div></footer>
  </section>;
}
