import { useMemo, useState } from "react";
import type { Project } from "../../types";
import TenantListLayout from "./TenantListLayout";
const formatDate = (value?: string) => value ? new Intl.DateTimeFormat("zh-CN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";
export default function TenantProjectList({ rows, organizationName, selectedId, onCreate, onMembers, onAddMember, onToggle, onEdit, onDelete }: { rows: Project[]; organizationName: string; selectedId: string; onCreate: () => void; onMembers: (item: Project) => void; onAddMember: (item: Project) => void; onToggle: (item: Project) => void; onEdit: (item: Project) => void; onDelete: (item: Project) => void }) {
  const [query, setQuery] = useState(""); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(10);
  const filtered = useMemo(() => rows.filter((item) => `${item.name} ${item.key}`.toLowerCase().includes(query.toLowerCase())), [query, rows]); const visible = filtered.slice((page - 1) * pageSize, page * pageSize);
  return <TenantListLayout title="项目空间列表" total={filtered.length} query={query} onQueryChange={(value) => { setQuery(value); setPage(1); }} searchPlaceholder="搜索项目名称或 Key..." actionLabel="新建项目" onAction={onCreate} page={page} pageSize={pageSize} onPageChange={setPage} onPageSizeChange={(size) => { setPageSize(size); setPage(1); }}><table className="w-full min-w-[1180px] text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-5 py-3">项目名称</th><th>成员</th><th>所属组织</th><th>状态</th><th>创建人</th><th>创建时间</th><th>描述</th><th className="pr-5 text-right">操作</th></tr></thead><tbody className="divide-y divide-slate-100">{visible.map((item) => <tr key={item.id} className={item.id === selectedId ? "bg-indigo-50/40" : "hover:bg-slate-50/70"}><td className="px-5 py-4 font-bold">{item.name}<div className="font-mono text-[10px] font-normal text-slate-400">{item.key}</div></td><td><button onClick={() => onMembers(item)} className="rounded-lg bg-indigo-50 px-2.5 py-1 font-bold text-indigo-700">{item._count?.members ?? 0}</button></td><td>{item.organization?.name || organizationName}</td><td><button onClick={() => onToggle(item)} className={item.status === "DISABLED" ? "text-rose-600" : "text-emerald-600"}>{item.status === "DISABLED" ? "禁用" : "启用"}</button></td><td>{item.auditLogs?.[0]?.actor?.displayName || "系统"}</td><td className="text-slate-500">{formatDate(item.createdAt)}</td><td className="max-w-xs truncate text-slate-500">{item.description || "—"}</td><td className="pr-5 text-right"><button onClick={() => onAddMember(item)} className="font-bold text-violet-600">添加成员</button><button onClick={() => onEdit(item)} className="ml-4 text-slate-500">编辑</button><button onClick={() => onDelete(item)} className="ml-4 text-rose-600">删除</button></td></tr>)}</tbody></table></TenantListLayout>;
}
