import { Pencil, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import type { OrganizationSummary } from "../OrganizationSpaceSettings";
import TenantListLayout from "./TenantListLayout";

const formatDate = (value?: string) => value ? new Intl.DateTimeFormat("zh-CN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";
export default function TenantOrganizationList({ rows, selectedId, onCreate, onMembers, onProjects, onAddUser, onToggle, onEdit, onDelete }: { rows: OrganizationSummary[]; selectedId: string; onCreate: () => void; onMembers: (item: OrganizationSummary) => void; onProjects: (item: OrganizationSummary) => void; onAddUser: (item: OrganizationSummary) => void; onToggle: (item: OrganizationSummary) => void; onEdit: (item: OrganizationSummary) => void; onDelete: (item: OrganizationSummary) => void }) {
  const [query, setQuery] = useState(""); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(10);
  const filtered = useMemo(() => rows.filter((item) => `${item.name} ${item.slug}`.toLowerCase().includes(query.toLowerCase())), [query, rows]);
  const visible = filtered.slice((page - 1) * pageSize, page * pageSize);
  return <TenantListLayout title="组织列表" total={filtered.length} query={query} onQueryChange={(value) => { setQuery(value); setPage(1); }} searchPlaceholder="搜索组织名称或标识..." actionLabel="新建组织" onAction={onCreate} page={page} pageSize={pageSize} onPageChange={setPage} onPageSizeChange={(size) => { setPageSize(size); setPage(1); }}><table className="w-full min-w-[980px] text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-5 py-3">组织名称</th><th>成员</th><th>项目</th><th>状态</th><th>创建人</th><th>创建时间</th><th className="pr-5 text-right">操作</th></tr></thead><tbody className="divide-y divide-slate-100">{visible.map((item) => <tr key={item.id} className={item.id === selectedId ? "bg-indigo-50/40" : "hover:bg-slate-50/70"}><td className="px-5 py-4 font-bold">{item.name}<div className="font-mono text-[10px] font-normal text-slate-400">{item.slug}</div></td><td><button onClick={() => onMembers(item)} className="rounded-lg bg-indigo-50 px-2.5 py-1 font-bold text-indigo-700">{item._count?.members ?? 0}</button></td><td><button onClick={() => onProjects(item)} className="rounded-lg bg-cyan-50 px-2.5 py-1 font-bold text-cyan-700">{item._count?.projectSpaces ?? 0}</button></td><td><button onClick={() => onToggle(item)} className={item.status === "DISABLED" ? "text-rose-600" : "text-emerald-600"}>{item.status === "DISABLED" ? "禁用" : "启用"}</button></td><td>{item.auditLogs?.[0]?.actor?.displayName || "系统"}</td><td className="text-slate-500">{formatDate(item.createdAt)}</td><td className="pr-5 text-right"><button onClick={() => onAddUser(item)} className="font-bold text-violet-600">添加用户</button><button onClick={() => onEdit(item)} className="ml-4 inline-flex items-center gap-1 text-slate-500"><Pencil className="h-3.5 w-3.5"/>编辑</button>{item.slug !== "default" && <button onClick={() => onDelete(item)} className="ml-4 inline-flex items-center gap-1 text-rose-600"><Trash2 className="h-3.5 w-3.5"/>删除</button>}</td></tr>)}</tbody></table></TenantListLayout>;
}
